README.md

Fixes the docker-compose remote path to point to the actual,raw file through GitHub's CDN.

fix(docs): update docker-compose installation uri

---

pyproject.toml
tests/test_parser.py

Closes #231  
This addresses the issue I raised in https://github.com/keephq/keep/issues/231.  I ran the tests and noticed the took a long time to run. I was able to isolate the long test run to a single test: test_parse_with_nonexistent_url @ 130s (ouch!)
The root cause of this test is due to `requests` attempting to make a request over the Internet to a url that doesn't exist. We don't need to test that `requests` tries to make the request and then throws the long awaited error. Or that the Internet isn't going to resolve a bad url. Let's focus on testing how this function handles `requests`'s thrown error.
I solved this by mocking the requests.get() call with an immediate raise of the error.  As the below shows, this drastically speeds up this test. You can now run all the unit tests …

fix: mock requests for bad url test

---

.gitignore
tests/test_parser.py

Added some tests around parsing providers from env vars.
There might be some behavior when parsing a malformed env var that is unintentional. See comments...

test: parse providers from env vars

---

keep-ui/app/providers/provider-form.tsx

Closes #426 
Added a document icon in the provider form; when clicked, it opens the doc of the current provider in the new tab.

feat(ui): added a provider documentation icon

---

keep/providers/opsgenie_provider/opsgenie_provider.py

Closes # 
Added scopes for OpsGenie provider
/claim #543

feat: added scopes-OpsGenie-provider

---

docker/Dockerfile.api
docker/Dockerfile.ui
keep/api/api.py

Dockerfile enhancement, posthog bugfix
posthog doesn't let application start if there is any connection issue, temporarily fixed it to atleast get the application in started mode.
Updated dockerfile for ui and api so that it can run seemlessly on openshift update dockerfile for api for caching layers more efficiently
Closes #

fix(startup): posthog issue when enabled and no connectivity

---

docker-compose-with-auth.yml
docker-compose-with-otel.yaml
docker-compose.common.yml
docker-compose.dev.yml
docker-compose.yml
docker/Dockerfile.dev.api

/close #531
- Templatization docker compose file
- Fixes Dockerfile.dev.api entry point
so that also calls config.py at the start of gunicorn server.
- Updates volume binding for backend in otel compose file

chore: docker-compose templatization

---

keep-ui/app/alerts/alert-history.tsx
keep-ui/app/alerts/alert-menu.tsx
keep-ui/app/alerts/alert-name.tsx
keep-ui/app/alerts/alert-table-utils.tsx
keep-ui/app/alerts/alerts-table-body.tsx

closes #690 
- fix skeleton shifting the table layout. the amount of skeleton cells sometimes superseded the visible columns, and when loading was finished, the whole table would shift as it removed the skeleton cells
- remove set width from the `name` col
- move menu to _right_ (typo in the commit 😬)
- history modal should stay open whenever a fingerprint alert is added. changed to use `fingerprint` as an identifier. the problem was that I used to select the alerts to view their history by their ID. but whenever a new fingerprint alert was pushed, `getFormatAndMergePusherWithEndpointAlerts` replaced the last alert with the most current. so the ID essentially changed in the `alerts` and thus the history modal closed since the ID in params was `undefined`. 
- removed the `loading` …

fix(ui): Column Width & History Modal

---

docker/Dockerfile.api

Responds to a [Slack thread](https://getkeep.slack.com/archives/C04PT44MATS/p1709500666995089?thread_ts=1709498421.593459&cid=C04PT44MATS) without the issue being referenced on Github
When one enable the backend ngrok feature through the `USE_NGROK=true` env variable, the python app ran by the low-priv user `keep` can't download ngrok binary inside `/venv/lib/python3.11/site-packages/pyngrok` and thus, can't enable the feature and cause the following : `PermissionError: [Errno 13] Permission denied: '/venv/lib/python3.11/site-packages/pyngrok/bin'`, ending the app.  
This PR aims to give the ownership of `keep` user over the `/venv` directory to circumvent this error. While this might not be the best of all fix security-wise, it works.
Might be worth to look twice before merging this, as …

build(api): chown `/venv` directory let the `keep` user install ngrok when enabled

---

keep/cli/cli.py

Closes #899
```
➜ ~  keep api -p 9090 -h "127.0.0.1" --help
Usage: cli.py api [OPTIONS]
Start the API.
Options:
--multi-tenant      Enable multi-tenant mode
-p, --port INTEGER  The port to run the API on
-h, --host TEXT     The host to run the API on
--help              Show this message and exit.
```

feat(cli): add port and host parameters to keep api command

---

keep-ui/app/workflows/models.tsx
keep-ui/app/workflows/workflow-tile.tsx

Closes #933 
Set workflow name as title of the workflow card and set 30 character limit.
Moved description to under the name with 50 character limit.
You can find how it looks like below:

feat(ui): use workflow name and description

---

keep/api/models/workflow.py

If workflow name is `<null>` in db workflow page doesn't come up this PR aims to fix that.

fix: make name optional to prevent ui errors in workflowdto

---

keep-ui/app/providers/provider-form.tsx
keep/api/routes/providers.py
keep/providers/newrelic_provider/newrelic_provider.py

Closes #1152
Added a validation that the api url starts with 'https' in `validate_config` of `NewrelicProvider`.
Old behaviour - 
Earlier it used to show this error instead of validating url.
New - 
Added `https` validation in the config, hence this meaningful `error_msg`.
- I am not sure if this is the expected fix.
Thanks

fix: Validates New Relic provider api url has https #1152

---

keep-ui/app/workflows/builder/editors.tsx
keep/providers/axiom_provider/axiom_provider.py
keep/providers/bash_provider/bash_provider.py
keep/providers/cloudwatch_provider/cloudwatch_provider.py
keep/providers/console_provider/console_provider.py
keep/providers/github_workflows_provider/github_workflows_provider.py
keep/providers/gitlabpipelines_provider/gitlabpipelines_provider.py
keep/providers/google_chat_provider/google_chat_provider.py
keep/providers/http_provider/http_provider.py
keep/providers/microsoft-planner-provider/microsoft-planner-provider.py
keep/providers/opsgenie_provider/opsgenie_provider.py
keep/providers/pagerduty_provider/pagerduty_provider.py
keep/providers/pagertree_provider/pagertree_provider.py
keep/providers/postgres_provider/postgres_provider.py
keep/providers/python_provider/python_provider.py
keep/providers/telegram_provider/telegram_provider.py
keep/providers/trello_provider/trello_provider.py
keep/providers/twilio_provider/twilio_provider.py
keep/providers/zenduty_provider/zenduty_provider.py

Closes #1179
1. Fixed the parameters for `_notify` and `_query` for the providers which were using `**kwargs`.
2. Fixed UI for the workflow builder page, video attached here - #1179 
1. AxiomProvider - 
1. _query - 
1. dataset
2. BashProvider - 
1. _query - 
1. timeout, command
3. CloudwatchProvider -
1.  _query - 
1. log_group, query, hours
4. ConsoleProvider -
1. _notify -
1. message
5. GithubWorkflowsProvider -
1. changed notify -> _notify, removed usage of kwargs to parameters -
1. github_url
2. github_method
6. GitlabpipelinsProvider - 
1. fixed spelling of it’s AuthConfig class, which was causing no parameters to appear in UI.
2. changed notify -> _notify, moved kwargs to parameters -
1. github_url
2. github_method
7. GoogleChatProvider -
1. changed notify -> _notify
8. HttpProvider …

fix: _notify and _query kwargs, params and UI step parameters/action params..

---

docs/providers/documentation/pagerduty-provider.mdx
keep/providers/mongodb_provider/mongodb_provider.py
keep/providers/pagerduty_provider/pagerduty_provider.py

Closes #1031 and #903
Added `validate_scopes` for `PagerdutyProvider`. 
Included the following scopes - 
1. `incidents.read`
2. `incidents.write`
3. `webhook_subscriptions.read`
4. `webhook_subscriptions.write`
Also fixed mongodb always validating scopes.
Pagerduty - 
If api key is wrong (Unauthorized) - 
If valid api key and authorized - 
Mongodb - 
If wrong URI - 
If right URI -

chore(provider): PagerDuty scopes added and fix: mongodb connection check

---

keep/api/core/db.py
tests/e2e_tests/test_end_to_end.py

When using `PostgreSQL` as backend database an error occur when converting datetime to string with the `to_char` `PostgreSQL` function as it expects a [specific formatting](https://www.postgresql.org/docs/current/functions-formatting.html#FUNCTIONS-FORMATTING)
This PR fix a bug that makes unusable the web application. On `Providers` page, the KPI displaying the number of alerts per integration crashed. Thus, it is impossible to manage integration because of query crashing in the backend.

fix: PostgreSQL datetime formatting with `to_char`

---

keep/api/models/db/extraction.py
keep/api/routes/extraction.py
tests/fixtures/client.py
tests/test_auth.py
tests/test_extraction_rules.py

While creating extraction rule it was throwing SQL error:
```json
{
"message": "An internal server error occurred.",
"trace_id": "x",
"error_msg": "(sqlite3.OperationalError) no such column: updated_at\n[SQL: INSERT INTO extractionrule (tenant_id, priority, name, description, created_by, created_at, updated_by, updated_at, disabled, pre, condition, attribute, regex) VALUES (?, ?, ?, ?, ?, ?, ?, updated_at, ?, ?, ?, ?, ?) /*db_driver='pysqlite',db_framework='sqlalchemy%%3A0.41b0',traceparent='x'*/]\n[parameters: ('keep', 0, 'asd', 'asd', 'admin@keephq', '2024-04-20 12:30:39.005900', None, 0, 0, '', 'asd', '(?P<groupname>)')]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)"
}
```
The issue was already mentioned in PR https://github.com/keephq/keep/pull/1132, but the solution …

fix: "no such column updated_at" during extraction creating

---

keep-ui/app/dashboard/[id]/dashboard.tsx
keep-ui/app/layout.tsx

If you mistakenly move dashboard widget too much down, it disappears from screen. 
Solved. The screen grows accordingly.

fix: dashboard overflow (#1283)

---

keep-ui/app/dashboard/styles.css
keep-ui/components/navbar/MinimizeMenuButton.tsx

On large screens, there is a MinimizeMenuButton to hide and display the menu, and for small screens, a Popover.Button.
However, both buttons are displayed on small screens by mistake, and due to the change of grid to flex MinimizeMenuButton takes up too much space.
Problem is solved.

fix: mobile mode (#1283)

---

keep/api/core/elastic.py
tests/test_search_alerts.py

Closes #1454 
Elastic doesn't know what fields were enriched. So we are getting enrichments after getting data from elastic

fix: Bulk enrich alerts when using elastic search

---

keep-ui/app/dark-mode-toggle.tsx
keep-ui/components/navbar/CustomPresetAlertLinks.tsx
keep-ui/components/navbar/Search.tsx
keep-ui/utils/hooks/useLocalStorage.ts

Hot-reload is essential to have a tight feedback loop during frontend development. Now it's broken due to a few hydration issues:
- invalid nesting (like button inside button)
- when using `useSyncExternalStore()` `getServerSnapshot()` is not provided
- `<ReactPlayer />` which uses browser-only APIs is rendered on server 
[<img src="https://cdn.loom.com/sessions/thumbnails/d5a28265ae334fdaacaba33714eeb120-fbf5d3d2d147bc9f.jpg" width="400"  /> <br/>Watch Loom with comparison](https://www.loom.com/share/d5a28265ae334fdaacaba33714eeb120)

fix: frontend hot-reload (hydration issues)

---

keep-ui/app/alerts/models.tsx
keep-ui/components/navbar/CustomPresetAlertLinks.tsx
keep-ui/utils/hooks/usePresets.ts

/claim #1163 
Closes #1163
If there is a private preset. we will check preset-created_by. if it matches the current session user then we will allow the preset on the UI or else we will ignore it.

fix: when preset is private it needs to filtered form the asset links

---

keep/workflowmanager/workflowmanager.py

fix(api): add bool to event_val filter

---

keep/api/core/db.py

Closes #1561
Now we have 2 definitions of the same function:
```
def get_incident_by_id(incident_id: UUID) -> Incident:
def get_incident_by_id(tenant_id: str, incident_id: str) -> Optional[Incident]:
```
Only 2nd definition is used. I suppose there are no much reasons to keep first one.

fix: core/db - remove unused function. closes #1561

---

keep-ui/app/incidents/[id]/incident-alerts.tsx
keep-ui/app/incidents/[id]/incident-info.tsx
keep-ui/app/incidents/[id]/incident.tsx
keep-ui/app/incidents/incident-candidate-actions.tsx
keep-ui/app/incidents/incident-table-component.tsx
keep-ui/app/incidents/incidents-table.tsx
keep-ui/app/incidents/model.ts
keep-ui/app/incidents/predicted-incidents-table.tsx
keep/api/models/alert.py

Closes #1572 
We need the ability to review the details of the predicted incident to make better decisions. This PR reuses the Incident details page, allowing us to see the details of Predicted Incidents and confirm/remove them right from this page.
Reduce code duplication for incidents

feat: Add predicted incident detail page

---

keep/api/models/db/migrations/versions/2024-07-25-17-13_67f1efb93c99.py

Closes #1592
Replace usage of imported AlertDto in migration "fields for prepopulated data from alerts" with the local simplified model.

fix: replace usage of imported AlertDto in migration

---

docs/providers/documentation/grafana-provider.mdx

Closes #1219
This pull request updates the Grafana provider documentation to include validation methods for scenarios where Keep is not accessible externally. The updated documentation provides alternative steps to validate the Grafana provider integration when the webhook cannot be used.
**Changes Made:**
- Added alternative validation methods for scenarios where Keep cannot be accessed from the outside.
- Enhanced instructions for configuring and testing the Grafana provider in restricted network environments.
- Clarified authentication and connection steps to ensure comprehensive coverage for all users.
- These changes were made to address issues with the current documentation's assumptions about Keep's accessibility.
- The updated documentation ensures users have clear guidance …

docs: add validation methods for Grafana provider when Keep is not accessible externally

---

keep/api/core/db.py
keep/api/models/db/migrations/versions/2024-08-14-18-30_87594ea6d308.py

fix: Incident severity is int, not string

---

docs/api-ref/groups/get-groups.mdx
docs/mint.json
docs/overview/ruleengine.mdx

Closes #1662
We don't have alert groups anymore. Correlation rules now create Incidents, and this PR updates documentation

feat: Remove alert groups mentions from the documentation

---

keep-ui/app/rules/CorrelationSidebar/index.tsx
keep/rulesengine/rulesengine.py
tests/test_rules_engine.py

Closes #1700 
To allow users to create rules with OR (alerts where `name contains GPU` or `name contains disk`) with grouping rules, we need to combine groups with OR instead of AND

feat: Rules' groups are now combined with || instead of &&

---

keep-ui/app/providers/provider-tile.tsx
keep-ui/app/providers/providers-tiles.tsx
tests/e2e_tests/test_end_to_end.py
tests/e2e_tests/test_pushing_prometheus_alerts.py

Closes #1738 
Hiding parts of UI on hover is not a great UX, the proposal is to remove buttons that appear on hover in favor of simply click on card itself and a gear icon for modify action.
[<img src="https://cdn.loom.com/sessions/thumbnails/7514fdf3ee2f40f9850e066688de5a49-1ff9ae7ce07faa01.jpg" width="400"  /> <br/>Watch Loom with comparison](https://www.loom.com/share/89f3b17fd44c4369a061782bfac9d84a)

feat: slightly different UX for provider tiles without hiding content on hover

---

keep/api/api.py
keep/api/routes/topology.py

close https://github.com/keephq/keep/issues/1789

fix(api): topology route mistakenly removed

---

docs/providers/documentation/victoriametrics-provider.mdx
examples/workflows/query_victoriametrics.yml
keep/providers/victoriametrics_provider/README.md
keep/providers/victoriametrics_provider/victoriametrics_provider.py

Closes #1829 
/claim #1829
Added option to query victoriametrics using query and query_range
https://github.com/user-attachments/assets/4c32023d-d33a-4e65-a7cd-04b07401dba7

feat: added query and query_range to VictoriaMetrics

---

tests/test_workflow_execution.py

fix: Trying to catch unstable test reason. Adding more observability by making workflow ids unique

---

keep/parser/parser.py
pyproject.toml

close https://github.com/keephq/keep/issues/1911

feat: inject env vars into provider provision json

---

keep/workflowmanager/workflowstore.py

close https://github.com/keephq/keep/issues/1931

fix: calculate common path correctly

---

keep-ui/app/alerts/alert-associate-incident-modal.tsx
keep-ui/app/incidents/create-or-update-incident.tsx
keep-ui/app/incidents/incidents-table.tsx

close https://github.com/keephq/keep/issues/2019

chore(incident): small cosmetic improvements

---

keep-ui/app/incidents/incidents-table.tsx
keep-ui/components/navbar/Navbar.css
keep-ui/components/navbar/Navbar.tsx

Stop hiding menu for small screen owners 😅:
Before:
After: 
+ readable incident page
Before:
After:
Closes https://github.com/keephq/keep/issues/2032

fix(ui): remove hiding navbar on MB Air-screen-size fixes

---

STRESS.md

Close #2097 
Fix grammatical errors in STRESS.md
Description:
I found a grammatical error in the STRESS.md of the project. This PR fixes the error to improve the overall readability and clarity of the documentation.
Changes:
Corrected grammatical error in line 38
Updated line 38  to reflect the correct grammar
Reasoning: The original text contained a grammatical error that could cause confusion for readers. This fix ensures that the documentation is accurate and easy to understand.

docs(STRESS.md): grammatical errors

---

keep-ui/app/rules/CorrelationSidebar/CorrelationForm.tsx
keep-ui/app/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
keep-ui/app/rules/CorrelationSidebar/index.tsx
keep-ui/app/rules/CorrelationTable.tsx
keep-ui/utils/hooks/useRules.ts
keep/api/core/db.py
keep/api/models/db/migrations/versions/2024-10-05-18-37_017d759805d9.py
keep/api/models/db/rule.py
keep/api/routes/rules.py
keep/rulesengine/rulesengine.py
tests/test_rules_api.py
tests/test_rules_engine.py

Closes #2087
Now, when provider sends alert with the same fingerprint multiple times with different statuses, user can configure when automatically resolve the Incident: when `all` associated alerts are resolved, when `first` or `last` alert is resolved or `never`. `Never` by default

feat: Implement auto resolution rules for incident correlations

---

keep/api/core/db.py

!-- 
Thanks for creating this pull request 🤗
Please make sure that the pull request is limited to one type (docs, feature, etc.) and keep it as small as possible. You can open multiple prs instead of opening a huge one.
-->
Closes #2141

fix(db): check if value is not empty while getting incidents meta (mysql dialect only)

---

keep/api/bl/enrichments_bl.py
tests/test_enrichments.py

close #2139
```
re.match() checks for a match only at the beginning of the string
re.search() checks for a match anywhere in the string (this is what Perl does by default)
```
https://docs.python.org/3/library/re.html#re.match
https://docs.python.org/3/library/re.html#re.search

fix: enrichments regex operation

---

keep/providers/splunk_provider/splunk_provider.py

fix: append api_key as a query parameter when setting Splunk webhook url

---

scripts/docs_get_providers_list.py

```
Exception: Provider "parseable" is not documented in the docs/providers/documentation folder,
please document it and run the scripts/docs_get_providers_list.py --validate script again.
Provider's PROVIDER_DISPLAY_NAME should match the title in the documentation file: {PROVIDER_DISPLAY_NAME}-provider.mdx.
parseable-provider.mdx not found.
Documented providers: ['azure aks', 'appdynamics', 'axiom', 'azure monitor', 'centreon', 'clickhouse', 'cloudwatch', 'console', 'coralogix', 'datadog', 'discord', 'elastic', 'gcp monitoring', 'github workflows', 'gitlab', 'gitlab pipelines', 'google chat', 'grafana', 'grafana incident', 'grafana oncall', 'http', 'ilert', 'incident.io', 'incident manager', 'jira on-prem', 'jira cloud', 'kibana', 'kubernetes', 'linear', 'linearb', 'mailchimp', …
```

fix: More verbose exception for provider docs validator

---

docs/deployment/configuration.mdx
docs/deployment/kubernetes.mdx

close https://github.com/keephq/keep/issues/2183

chore(docs): fix k8s and configuration

---

keep-ui/app/globals.css
keep-ui/app/providers/provider-form.tsx
keep-ui/app/providers/providers-tiles.tsx

fix: do not reload the page on the webhook installation

---

keep/contextmanager/contextmanager.py
keep/providers/base/base_provider.py
tests/test_contextmanager.py
tests/test_workflow_execution.py

Closes #2149 
Variable name:  `KEEP_PROVIDER_{}_LOG_LEVEL`

feat: User can set exact provider log level using environment variable

---

keep/workflowmanager/workflowmanager.py

chore: improve workflow on_failure behaivour

---

keep-ui/app/alerts/alert-timeline.tsx
keep-ui/app/incidents/[id]/incident-activity.css
keep-ui/app/incidents/[id]/incident-activity.tsx
keep-ui/app/incidents/[id]/incident-info.tsx
keep-ui/app/incidents/[id]/incident.tsx
keep-ui/app/settings/auth/users-table.tsx
keep-ui/app/topology/model/useTopology.ts
keep-ui/app/topology/model/useTopologyApplications.ts
keep-ui/components/navbar/UserAvatar.tsx
keep-ui/components/navbar/UserInfo.tsx
keep-ui/utils/hooks/useAlerts.ts
keep-ui/utils/hooks/useDashboards.ts
keep-ui/utils/hooks/useIncidents.ts
keep-ui/utils/hooks/useWorkflowExecutions.ts
keep/api/core/db.py
keep/api/models/db/alert.py
keep/api/routes/incidents.py

https://github.com/user-attachments/assets/6c3ad3b8-f370-467e-8ea2-8689cd567978

feat(incident): activity tab

---

keep/providers/netdata_provider/netdata_provider.py

Copy/Paste error fixed in netdata provider
attempt of ingesting events ended up with:
```
File "/venv/lib/python3.11/site-packages/keep/api/tasks/process_event_task.py", line 528, in process_event
event = provider_class.format_alert(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/venv/lib/python3.11/site-packages/keep/providers/base/base_provider.py", line 342, in format_alert
formatted_alert = cls._format_alert(event, provider_instance)                     
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/venv/lib/python3.11/site-packages/keep/providers/netdata_provider/netdata_provider.py", line 75, in _format_alert   
event[\"status\"][\"text\"], AlertStatus.INFO
^^^^^^^^^^^^^^^^  
File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__  
raise AttributeError(name) from None …
```

fix: copy/paste error with AlertStatus enum usage

---

keep/api/models/db/migrations/versions/2024-10-22-10-38_8438f041ee0e.py
pyproject.toml

close https://github.com/keephq/keep/issues/2277

fix(migrations): db's other than sqlite

---

examples/workflows/cron-digest-alerts.yml
keep/contextmanager/contextmanager.py
keep/providers/keep_provider/keep_provider.py
pyproject.toml

close https://github.com/keephq/keep/issues/2285

fix: workflow last run time

---

docs/deployment/configuration.mdx
docs/deployment/ecs.mdx
docs/deployment/stress-testing.mdx
docs/overview/comparisons.mdx
docs/overview/deduplication.mdx

Closes #2289
This PR fixes typos on the following pages of the Keep Docs site.

docs: Fix typos on multiple pages of Keep Docs Site

---

keep-ui/app/incidents/[id]/incident-activity.tsx

close https://github.com/keephq/keep/issues/2290

fix(ui): incident add a comment uses old API

---

keep/api/routes/alerts.py
pyproject.toml

/close #2292
In `_enrich_alert` function, you have the following parameter:
```python
dispose_on_new_alert: Optional[bool] = Query(False, description="Dispose on new alert")
```
Here, you're using `Query`, which is designed to be used in FastAPI endpoint functions to declare query parameters. When you use `Query`, FastAPI expects to parse this parameter from the incoming HTTP request.
However, `_enrich_alert` is not an endpoint function; it's a helper function that's being called directly from another function (`enrich_alert`). Seems like FastAPI's dependency injection system isn't in play for `_enrich_alert`, and `dispose_on_new_alert` is not being set from the HTTP request query parameters. Instead, **it's getting assigned the Query object itself as the default value**.  Since …

fix: alert enriching is always disposable (no matter query params)

---

keep-ui/components/navbar/DashboardLink.tsx
keep-ui/components/navbar/DashboardLinks.tsx

Closes #2315 
https://github.com/user-attachments/assets/21265f80-8ddd-4b7a-a21a-c1cae8b1acae

fix: hovering long dashboard names stretch NavBar

---

keep/api/models/db/alert.py
keep/api/models/db/migrations/versions/2024-11-03-10-49_ef0b5b0df41c.py
pyproject.toml

close https://github.com/keephq/keep/issues/2376

feat(api): add index on alert table

---

docs/deployment/kubernetes/installation.mdx
pyproject.toml

close https://github.com/keephq/keep/issues/2503

feat(docs): add docs for haproxy

---

docs/providers/documentation/statuscake-provider.mdx
keep/providers/statuscake_provider/statuscake_provider.py

feat: StatusCake Webhook integration

---

keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py

close https://github.com/keephq/keep/issues/2518

fix: minor fix in gcp monitoring

---

docs/providers/documentation/appdynamics-provider.mdx
keep/providers/appdynamics_provider/appdynamics_provider.py

feat: provider appdynamics integration using access_token

---

keep/providers/appdynamics_provider/appdynamics_provider.py

Such a massive pr
Closes https://github.com/keephq/keep/issues/2533

fix: Response content for AppD

---

keep-ui/app/(keep)/topology/api/index.ts
keep-ui/app/(keep)/topology/model/useTopology.ts
keep-ui/app/(keep)/topology/model/useTopologyApplications.ts
keep-ui/utils/hooks/usePresets.ts
keep-ui/utils/state.ts
keep/api/core/db.py
keep/api/routes/preset.py
keep/api/tasks/process_event_task.py

fix: feed counter

---

keep-ui/app/api/auth/[...nextauth]/route.ts
keep-ui/auth.config.ts
keep-ui/auth.ts
keep-ui/middleware.tsx
proxy/squid.conf

fix(auth): fix preview environments

---

keep/identitymanager/authverifierbase.py

None
Closes https://github.com/keephq/keep/issues/2669

fix:Multiple bypass keys

---

keep/api/core/dependencies.py
keep/api/routes/alerts.py
keep/api/tasks/process_event_task.py
keep/identitymanager/identitymanagerfactory.py
pyproject.toml

close https://github.com/keephq/keep/issues/2694

feat(api): more verbose

---

docker/Dockerfile.api
keep/entrypoint.sh

Build providers cache on startup and not on build time (no env variables then). Adds a few seconds to start time.

fix: oauth2 not working due to providers caching

---

keep/parser/parser.py
keep/providers/slack_provider/slack_provider.py

Slack does not work with OAuth anymore because of the new validation method, reverting https://github.com/keephq/keep/pull/2430 for slack

fix: revert validation for Slack provider to work with oauth

---

keep/parser/parser.py

fix: Add check for None in providers provisioning form env var

---

keep-ui/features/incident-list/ui/incident-table-component.tsx
keep-ui/features/incident-list/ui/incidents-table.tsx
keep-ui/next.config.js

fix: frontend warnings

---

docs/deployment/configuration.mdx
keep/api/api.py
keep/api/core/dependencies.py
keep/api/core/limiter.py
keep/api/core/metrics.py
keep/api/custom_worker.py
keep/api/routes/alerts.py
keep/api/routes/metrics.py
poetry.lock
pyproject.toml

feat(api): simple rate limiting with slowapi

---

keep-ui/app/(keep)/providers/page.client.tsx
keep-ui/app/(signin)/layout.tsx
keep-ui/app/(signin)/signin/SignInForm.tsx
keep-ui/features/incident-list/ui/incident-list-error.tsx
keep-ui/middleware.ts
keep-ui/shared/api/ApiClient.ts
keep-ui/shared/api/server/createServerApiClient.ts
keep-ui/shared/lib/hooks/useApi.tsx
tests/e2e_tests/test_end_to_end.py

Closes #2584  
1. Sign out user if the API returned 401 on client
2. If user is authenticated, redirect to callbackUrl if it present
3. Polish SingInForm design
4. Use common layout for initial state

fix: redirect on 401

---

keep-ui/app/(keep)/incidents/page.tsx
keep-ui/entities/incidents/model/models.ts
keep-ui/entities/incidents/ui/statuses.tsx
keep-ui/features/change-incident-status/ui/incident-change-status-select.tsx
keep-ui/features/incident-list/ui/incident-table-filters-context.tsx
keep/api/bl/incidents_bl.py
keep/api/core/db.py
keep/api/models/alert.py
tests/test_incidents.py

feat: Add soft-delete for incidents through the status

---

keep/providers/opsgenie_provider/opsgenie_provider.py
pyproject.toml

fix(opsgenie): retry 404 again

---

keep/api/logging.py
pyproject.toml

close https://github.com/keephq/keep/issues/2940

fix(api): logs leak

---

keep-ui/auth.config.ts
keep/api/core/db.py
pyproject.toml

close https://github.com/keephq/keep/issues/2944

fix(api): postgres dashboards

---

keep-ui/app/(keep)/alerts/alerts-table-body.tsx
keep-ui/features/incident-list/ui/incident-table-component.tsx

fix: alert table theming and hover

---

keep/api/tasks/process_event_task.py

close #2974 
in one of the conditions of the process_event function there is a flaw in processing event as a list. 2 months ago there was no such problem, but now when I upgraded the version of keep I found that zabbix provider started getting an error. while studying the issue (2 days) I finally understood what was the problem. The point is that in one of the conditions there is an attempt to convert dict into some formatted model, but the check condition checks list as well, without even trying to understand what is inside. The base_provider function requires implementing _format_alert, where event=dict. This means that you cannot pass list, or even list[alertDTO]. The change ensures that the _format_alert call is excluded if it is not dict.
```python
@staticmethod
def _format_alert( …
```

fix: event as list[AlertDTO]  not included in the condition

---

keep/api/consts.py
keep/api/routes/preset.py

At the moment, keep prefers to work with webhook from source systems. But my company prefers to initiate a request from keep (for example, Oracle Enterprise Management). In view of this, it is problematic to have a limitation in a variable "KEEP_PULL_INTERVAL", which represents days. As more flexibility, it would be better to give users the ability to configure the pulling time themselves (for example, in minutes). Of course, ideally for the pull data option, it is best to have such a variable in the provider itself, but as an intermediate flexible solution, I suggest considering giving users the freedom to configure data collection from sources themselves.
close #2975

feat(api): change calculation variable for pull data from providers

---

keep/api/logging.py
pyproject.toml
tests/test_workflow_execution.py

close https://github.com/keephq/keep/issues/2987

fix(api): workflowdb handler

---

keep/api/core/posthog.py
keep/cli/cli.py

close https://github.com/keephq/keep/issues/2986

fix: posthog to None if disabled

---

keep/api/core/limiter.py
pyproject.toml

close https://github.com/keephq/keep/issues/3019

fix(api): add limit log

---

keep/actions/actions_factory.py
keep/api/models/workflow.py
keep/api/routes/actions.py
keep/api/routes/workflows.py
keep/cli/cli.py
keep/functions/cyaml.py
keep/parser/parser.py
keep/providers/aks_provider/aks_provider.py
keep/providers/sendgrid_provider/sendgrid_provider.py
keep/workflowmanager/workflowstore.py
tests/test_parser.py

fix: yaml.safe_load is slow as hell

---

keep-ui/app/(keep)/incidents/page.tsx
keep-ui/entities/incidents/api/incidents.ts
keep-ui/features/filter/add-facet-modal.tsx
keep-ui/features/filter/facet-panel-server-side.tsx
keep-ui/features/filter/facet.tsx
keep-ui/features/filter/facets-panel.tsx
keep-ui/features/incident-list/ui/incident-list.tsx
keep-ui/features/incident-list/ui/incidents-not-found.tsx
keep/api/models/facet.py

fix(ui,be): minor bugs on Incidents after facets

---

keep/providers/victoriametrics_provider/victoriametrics_provider.py
pyproject.toml

close https://github.com/keephq/keep/issues/3106

fix(vm): skip validate scopes

---

keep/providers/kibana_provider/kibana_provider.py
pyproject.toml

close https://github.com/keephq/keep/issues/3221

feat: kibana 8.16.0

---

keep/api/config.py
keep/api/logging.py

close https://github.com/keephq/keep/issues/3266

fix(api): logs

---

keep-ui/features/filter/facets-panel.tsx
keep-ui/utils/hooks/useIncidents.ts

fix: Fix buggy incident facets

---

keep/api/bl/ai_suggestion_bl.py
keep/api/core/db.py

fix(api): event_id to fingerprint

---

keep-ui/app/(signin)/signin/SignInForm.tsx
keep-ui/app/(signin)/signin/page.tsx
keep-ui/middleware.ts

Closes #3289
Use callbackUrl query param to navigate the user to requested URL after sign-in

fix(auth): add callbackUrl parameter for redirect after sign-in

---

keep-ui/components/navbar/IncidentLinks.tsx
keep/api/models/db/migrations/versions/2025-02-05-15-46_e343054ae740.py

Updated the IncidentLinks component to exclude incidents with 'deleted' or 'resolved' statuses from the navbar list. This ensures only relevant incidents are displayed to the user.
Closes #3322

fix: Filter out deleted and resolved incidents in navbar links.

---

keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
pyproject.toml

close https://github.com/keephq/keep/issues/3293

fix(api): save button

---

examples/workflows/opsgenie-create-alert.yml
keep-ui/components/navbar/UserAvatar.tsx
keep-ui/entities/users/ui/UserStatefulAvatar.tsx
keep/providers/coralogix_provider/coralogix_provider.py
tests/test_workflow_execution.py

close keep alert: 2e8ee15760f9246a328074c123e0cec2d7663d8c9187d1e47fc5c221f966d3cd

fix(ui): assignee to show on hover

---

docs/providers/documentation/site24x7-provider.mdx

close #3369 
Adds a remark to the Site24x7 docs to ensure you use the correct Zoho account URI for generating the refresh token.

docs(site24x7): add remark of using correct account uri

---

keep/providers/grafana_incident_provider/grafana_incident_provider.py

close #3382
This _loosens_ the validation of the `Host` field on the Grafana Incident provider, matching that of the normal Grafana provider. 
While it is good to use HTTPS where possible, for certain use-cases it might not be possible/desirable (e.g. linking to services on K8s that use their ingress to do SSL termination).

chore: loosen validation on host url of grafana-incident

---

keep/api/models/db/migrations/versions/2025-02-11-12-59_21d314490e6a.py

Ensure `json.loads` is only called on string types to prevent type errors during migration. This update adds a type check for better robustness and handles non-string matcher inputs correctly.
Closes #3473

fix: JSON loading in migration script

---

keep-ui/app/(keep)/providers/provider-form.tsx
keep-ui/app/(keep)/providers/providers.tsx
keep/api/models/provider.py
keep/providers/providers_factory.py

Integrated logic and UI updates to distinguish if a provider supports pulling alerts. Introduced the `pulling_available` flag for providers, ensuring the "Pulling Enabled" checkbox only appears when applicable. Updated models, factory, and form components to reflect this functionality.
Closes #3243

fix: Add pulling availability support for providers

---

keep/api/core/db.py
keep/api/routes/incidents.py

For PostgreSQL: rowcount will be 0 because PostgreSQL doesn't count rows where no actual change was needed.
So, changing status to the same status for the incident caused 500 on PG. Removed the rowcount check because no need.
close https://github.com/keephq/keep/issues/3512

fix: 500 on incident status change

---

keep/rulesengine/rulesengine.py

Replaced rule-based logic with incident-based logic for determining resolution, removing the `rule` parameter from the `_resolve_incident_if_require` method. This improves code clarity and aligns resolution checks directly with the incident object.
Closes #3508

fix: Refactor incident resolution to remove rule dependency

---

keep-ui/app/(keep)/alerts/alert-associate-incident-modal.tsx
keep-ui/app/(keep)/alerts/alert-create-incident-ai-modal.tsx
keep-ui/app/(keep)/alerts/alert-table-facet-value.tsx
keep-ui/components/navbar/IncidentLinks.tsx
keep-ui/features/incident-list/ui/incident-list.tsx
keep-ui/features/same-incidents-in-the-past/ui/change-same-incident-in-the-past-form.tsx
keep-ui/features/split-incident-alerts/ui/split-incident-alerts-modal.tsx
keep-ui/utils/hooks/useIncidents.ts
keep/api/routes/incidents.py

Updated the `useIncidents` hook and related API to include an optional `predicted` filter for improved incident querying capabilities. Adjusted all relevant components to pass the new parameter where applicable, ensuring consistent functionality across the application.
Closes #3504

fix: Add optional 'predicted' filter support in useIncidents hook

---

keep-ui/app/(keep)/alerts/alert-table-utils.tsx

fix: allow up to 3 lines in alert description

---

keep-ui/app/(keep)/alerts/ViewAlertModal.tsx

Replace direct references to monaco-editor's types with generic `any` types to decouple the component from the monaco-editor package. This simplifies the code by reducing dependency-specific bindings, but may slightly reduce type safety.
Closes #3538

fix: Refactor ViewAlertModal to remove monaco-editor dependency

---

keep/api/models/alert.py
keep/api/models/db/migrations/versions/2025-02-18-18-09_876a424d8f06.py
keep/api/routes/alerts.py

Commented out direct status update in alert model and adapted enrichment logic to ensure dismissed alerts are tagged with SUPPRESSED status. Added a database migration to retroactively update enrichment statuses and modified the enrichment route to handle this condition dynamically.
Closes #3530

fix: Refactor dismissed enrichments to handle SUPPRESSED status

---

keep-ui/app/(keep)/alerts/alert-associate-incident-modal.tsx
keep-ui/app/(keep)/alerts/alert-grouped-row.tsx
keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
keep-ui/app/(keep)/alerts/alert-table.tsx
keep-ui/app/(keep)/alerts/alerts-table-body.tsx
keep-ui/app/(keep)/incidents/[id]/activity/incident-activity.tsx
keep-ui/app/(keep)/incidents/[id]/activity/ui/IncidentActivityComment.tsx
keep-ui/app/(keep)/incidents/[id]/activity/ui/IncidentActivityItem.tsx
keep-ui/app/(keep)/incidents/[id]/timeline/incident-timeline.tsx
keep-ui/app/(keep)/workflows/manual-run-workflow-modal.tsx
keep-ui/entities/incidents/lib/utils.ts
keep-ui/entities/incidents/model/useIncidentActions.tsx
keep/api/models/db/alert.py
keep/api/routes/alerts.py
keep/api/routes/incidents.py

close #3549 
close #3548 
- Fixed incident status change to acknowledge to ack alerts too
- Looking at some alert will show an icon that this alert was viewed before and highlight the last alert that was looked at
- Alert self-assign changes the alert status to acknowledged
- Incident status change audit message
- Incident status change assignes changing user
- Removed fingerprint from AlertEventInfo
- Workflow execution doesn't take you to the execution but proposes in Toast
- Filter resolved and deleted incidents with alert association modal

chore: several improvements based on feedback

---

keep-ui/features/incident-list/ui/incident-list.tsx
keep-ui/features/incident-list/ui/incidents-table.tsx

Introduce a date range picker for the incident list, allowing users to filter incidents by creation time. Refactor filtering logic to include the new date range and integrate it with existing filters. Add a clear filter handler to reset all filters, including the date range.
Closes #3553

feat: Add date range filter to incident list

---

keep/api/models/db/migrations/versions/2025-02-25-14-20_a82154690f35.py
keep/api/models/db/topology.py

Ensure `description` and `repository` in `TopologyApplication` are non-nullable in the database and models by setting default values for missing entries. Updated migration script and adjusted model definitions accordingly.
Closes #3668

fix: Make `description` and `repository` not-nullable.

---

keep-ui/app/(keep)/topology/ui/map/topology-map.tsx
keep/api/models/db/topology.py
keep/topologies/topologies_service.py
tests/test_topology.py

Add `clean_before_import` to remove tenant-specific data before topology imports, ensuring a clean slate. Updated `import_to_db` to call this function and added corresponding tests to validate behavior.
closes keep incident: a59d7701-22a3-4262-9651-dec6021b890d
Closes #3698

fix: Add cleanup function for tenant data before topology import

---

keep/providers/grafana_provider/grafana_provider.py

Added fallback to None for URL-related fields when they are undefined. This ensures safer and more consistent handling of empty or missing values.
Closes #3709
closes keep incident: 98fea67a-5a6b-44ae-afcb-4178f1842321

fix: Handle None values for Grafana provider URLs

---

keep-ui/app/(keep)/extraction/[rule_id]/executions/[execution_id]/page.tsx
keep-ui/app/(keep)/mapping/[rule_id]/executions/[execution_id]/page.tsx

Updated alert filter logic to accommodate variations in alert_id format. This ensures compatibility with different storage formats in enrichment events.
Closes #3518

fix: Handle both dashed and non-dashed alert_id formats.

---

keep-ui/entities/workflows/lib/__tests__/yaml-utils.test.ts
keep/functions/cyaml.py
tests/test_cyaml.py

Closes #3826  
```yaml
id: query-clickhouse
description: Query Clickhouse and send an alert if there is an error
triggers:
- type: manual
steps:
- name: clickhouse-observability-urls
provider:
config: "{{ providers.clickhouse }}"
type: clickhouse
with:
query: |
SELECT Url, Status FROM "observability"."Urls"
WHERE ( Url LIKE '%te_tests%' ) AND Timestamp >= toStartOfMinute(date_add(toDateTime(NOW()), INTERVAL -1 MINUTE)) AND Status = 0;
- name: clickhouse-observability-events
provider:
config: "{{ providers.clickhouse }}"
type: clickhouse
with:
query: |
SELECT arrayElement(Metrics.testName, 1) AS mytest FROM observability.Events
WHERE (Sources = 'ThousandEyes') AND (Timestamp >= toStartOfMinute(toDateTime(NOW()) + toIntervalMinute(-1))) AND (mytest = 'Oceanspot-TE')
- name: …
```

fix: multiline strings starting with "|"

---

keep-ui/features/filter/facet-panel-server-side.tsx
keep-ui/features/filter/facets-panel.tsx
keep-ui/features/filter/models.tsx
keep-ui/features/incident-list/ui/incident-list.tsx

Closes #3641
- Move uncheckedByDefaultOptionValues to FacetConfig interface

fix: Clear filters in incidents does not reset default facets

---

keep/api/core/db.py
tests/conftest.py
tests/test_incidents.py

Update incident start and last seen times to use the "lastReceived" field from alerts instead of "timestamp". Added parsing logic for string timestamps and a test to validate the timestamp handling based on varied alert data.
Closes #3822

fix: Refactor timestamp handling for incident alerts

---

keep/api/core/db.py
tests/test_rules_engine.py

This change ensures the `resolve_on` field is properly set when creating incidents. It improves data consistency and supports future use cases that depend on this attribute.
Closes #3913

fix: Add `resolve_on` field to incident creation for grouping rule

---

keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
keep-ui/app/(keep)/incidents/[id]/activity/incident-activity.tsx
keep-ui/app/(keep)/rules/CorrelationSidebar/RuleFields.tsx
keep-ui/app/(keep)/rules/CorrelationSidebar/RuleGroup.tsx
keep-ui/app/(keep)/rules/CorrelationTable.tsx
keep-ui/entities/presets/model/usePresetActions.ts
keep-ui/features/change-incident-status/ui/incident-change-status-select.tsx
keep-ui/package-lock.json
keep-ui/package.json
keep/api/bl/enrichments_bl.py
keep/api/core/db.py
keep/api/routes/alerts.py
keep/api/routes/incidents.py

close #3971 
- Incident activity duplicate entries (filtering out non relevant actions)
- Change incident status performance: bulk update alerts
- != default operator
- Upgrade react-querybuilder to fix a few bugs

fix: several issues in incidents and correlation rule builder

---

keep/api/bl/enrichments_bl.py
keep/api/bl/incidents_bl.py
keep/api/routes/incidents.py

Separated the incident status change functionality into a dedicated method within `incident_bl` for improved modularity and readability. This reduces redundancy in `routes/incidents.py` and centralizes the business logic for incident handling. Additionally, adjusted enrichment metadata retrieval and added necessary imports for consistency.
Closes #4000

fix: Refactor incident status change logic to incident_bl.

---

keep-ui/app/(keep)/workflows/[workflow_id]/workflow-sync-status.tsx
keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
keep-ui/features/workflows/test-run/ui/builder-workflow-testrun-modal-content.tsx
keep-ui/package-lock.json
keep-ui/package.json
keep-ui/shared/api/ApiClient.ts
keep-ui/widgets/workflow-builder/workflow-builder-widget.tsx
tests/e2e_tests/test_end_to_end.py

Closes #4078 
Before:
https://github.com/user-attachments/assets/00275178-de5b-4b14-8fcd-23831886740b
After:
https://github.com/user-attachments/assets/8cc75d48-74cd-4f53-8ce7-1b15d76c5bdb

fix: remove outdated 'react-loading'

---

docker/Dockerfile.ui
ee/identitymanager/identity_managers/auth0/auth0_authverifier.py
keep-ui/auth.config.ts
keep-ui/auth.ts
keep-ui/components/navbar/Menu.tsx
keep-ui/components/navbar/Navbar.tsx
keep-ui/components/navbar/Search.tsx
keep-ui/next.config.js
keep-ui/types/auth.d.ts
keep-ui/utils/hooks/usePusher.ts
keep/identitymanager/identity_managers/noauth/noauth_authverifier.py
pyproject.toml
tests/test_auth_new.py

close https://github.com/keephq/keep/issues/4106

feat: switch tenants

---

keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx

Corrected the logic for the isCandidate prop by aligning its value with the `incident.is_candidate` field. This ensures the component behaves as expected based on the incident's candidate status.
Closes #4075

fix: incorrect isCandidate prop in IncidentAlerts component

---

keep/api/api.py
keep/api/arq_worker.py

Introduced a safe_run_worker function to manage Redis connection errors with retries, enhancing worker reliability. Updated task pool execution to use safe_run_worker instead of async_run, ensuring improved fault tolerance during Redis failures.
Closes #4155

fix: Add safe_run_worker to handle Redis connection errors

---

keep/api/core/db.py
keep/api/models/db/incident.py
keep/api/tasks/process_event_task.py
tests/test_incidents.py

Added a helper method `get_active` to the `IncidentStatus` model to identify active statuses. Updated incident resolution to only apply to incidents with active statuses. Added test cases to validate the behavior and refactored session handling in `create_incident_from_dict`.
Closes #4158

fix: Refactor incident resolution logic to handle active statuses.

---

keep/api/core/db.py

Introduced retry logic to address StaleDataError during `session.commit` in `update_key_last_used` and `add_alerts_to_incident` functions. This ensures resilience against phantom reads by retrying up to a maximum number of attempts. Added `max_retries` parameter to allow configuration of retry limits.
Closes #4152

fix: Handle StaleDataError with retries in database updates.

---

keep/api/bl/incidents_bl.py
keep/api/core/db.py
keep/api/tasks/process_event_task.py

Added break statements to exit loops after successful commit operations, preventing infinite retries in case of StaleDataError or similar exceptions. Also refactored incident resolution logic in `process_event_task.py` for efficiency by reusing the IncidentBl object.
Closes #4160

fix: retry loops by adding break statements after commits

---

keep-ui/app/(keep)/alerts/alert-create-incident-ai-card.tsx
keep-ui/app/(keep)/alerts/alert-create-incident-ai-modal.tsx
keep-ui/app/(keep)/alerts/alert-sidebar.tsx
keep-ui/app/(keep)/incidents/[id]/timeline/incident-timeline.tsx
keep-ui/entities/alerts/model/models.tsx
keep-ui/entities/incidents/model/models.ts
keep-ui/shared/ui/FormattedContent/FormattedContent.tsx
keep/api/models/alert.py

Closes #4167
Add HTML & Markdown compatibility in Keep's alert description.
Configuring the below description format will result in the markdown formatted:
```bash
"description": "### High CPU Usage Detected\n\n**Server:** web-server-1\n**Time:** 2024-03-21 14:30 UTC\n**Usage:** 95%\n\n#### Details\n- Current Usage: 95%\n- Threshold: 80%\n- Duration: 15 minutes\n\n##### Recommended Actions\n1. Check running processes\n2. Review recent deployments\n3. Scale up resources if needed",
"description_format": "markdown"
```
Configuring the below description format will result in the html formatted:
```bash
"description": "<div class=\"prose prose-slate\"><h2>Database Connection Failed</h2><p>Multiple connection attempts to the primary database have failed.</p><h3>Error …
```

feat: add html & markdown compability in alert's description

---

docs/deployment/provision/provider.mdx
keep/api/alert_deduplicator/deduplication_rules_provisioning.py
keep/api/models/provider.py
tests/deduplication/test_deduplications_provisioning.py

Closes #4175
Currently, there is a mismatch between the key of `all_providers_dict` and `provider_dict_key`: the provider display name is not equal to the provider name.
The provider provisioning already uses the provider name as an identity: https://github.com/keephq/keep/blob/04fdc95226696e43d52d51d8d24dc0c24c29f101/keep/providers/providers_service.py#L392
Therefore, we can cascade this to the deduplication rules provisioning.

fix(provision): Use the provider name as the key in the deduplication rules enrichment logic

---

keep/api/bl/enrichments_bl.py
keep/api/routes/alerts.py
keep/providers/base/base_provider.py
tests/conftest.py
tests/test_enrichments.py

fix: incident not resolved when alerts enriched from workflow

---

keep/api/bl/incidents_bl.py
keep/api/core/db.py
tests/test_incidents.py
tests/test_metrics.py

The function was redundant and removed to simplify the codebase. All calls were replaced with add_alerts_to_incident, improving consistency and code maintainability across modules and tests.
Closes #4204

fix: refactor add_alerts_to_incident and remove add_alerts_to_incident_by_incident_id function

---

keep/providers/base/base_provider.py

Previously, the resolution check only considered `_enrichments`. This update expands it to also account for `disposable_enrichments` status to ensure more comprehensive incident handling logic.
Closes #4211

fix: incident resolution check in enrich_alert step

---

keep/api/core/alerts.py

This pull request fixes the following **SQLAlchemy warning** in Keep:  
```
/venv/lib/python3.11/site-packages/keep/api/core/alerts.py:184: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
```  
The issue occurs because a **SELECT object is being implicitly coerced** when a scalar subquery is expected.  
- Updated the affected query in `alerts.py` to explicitly use `.scalar_subquery()`, ensuring compatibility with SQLAlchemy’s best practices.  
- This prevents unnecessary warnings and potential future incompatibility with newer SQLAlchemy versions.  
Closes #4275

fix: Explicitly Use .scalar_subquery() to Prevent SQLAlchemy Warning

---

keep-ui/app/(keep)/alerts/alert-sidebar.tsx
keep-ui/app/(keep)/providers/provider-tile.tsx
keep/api/utils/enrichment_helpers.py

Closes #4271
When provisioning a provider and sending an alert with an incorrect providerId (one that does not belong to the provisioned provider), the alert gets permanently associated with the wrong provider.
If the same alert is sent again (with partial deduplication) using the correct providerId, it still retains the previously assigned incorrect `providerId`. We should allow the providerId to be updated to the latest value.
Here’s a clearer and more polished version of your text:  
I have configured alerts to be sent to Keep via a generic webhook endpoint. For the provisioned provider **A** with ID `123`, I decided to add the query parameter `?provider_id=123`.  
On the **Provider** page, each provider card was incorrectly displaying the `id` field instead of the `name` field. I have …

feat: allow using latest providerId and alter UI display

---

docs/snippets/providers/telegram-snippet-autogenerated.mdx
examples/workflows/telegram_advanced.yml
examples/workflows/telegram_basic.yml
keep/providers/telegram_provider/telegram_provider.py

Closes #4331
Telegram allows users to send messages within a topic and add reply markup for embedding links.
```yaml
workflow:
id: telegram-message-topic-markup
name: Telegram Message Sender with Topic Markup
description: Send messages into Telegram topic with a message containing a reply markup.
triggers:
- type: manual
actions:
- name: telegram
provider:
type: telegram
config: "{{ providers.telegram }}"
with:
message: "message with topic markup"
chat_id: "-1001234567890"
topic_id: "1234"
reply_markup:
📌 Confluence 📖:
url: "https://confluence.example.com"
📖 Documentation 📖:
url: "https://docs.example.com"
```

feat: add support for topic sending and inline keyboard markup in Telegram message

---

keep/providers/openobserve_provider/openobserve_provider.py

Replaced the variable `name` with `alert_name` for improved readability and added `row_name` to construct more descriptive alert names when available. This ensures alert details are clearer and more context-specific.
Closes #4402

fix: Allow OpenObserve to pass row name, which extends alert name

---

docs/deployment/configuration.mdx
keep-ui/app/api/copilotkit/route.ts
keep/api/bl/ai_suggestion_bl.py
keep/api/bl/incident_reports.py
keep/api/consts.py

Closes #4379 
Allow configuring OpenAI model by setting `OPENAI_MODEL_NAME` environment variable.
```bash
OPENAI_MODEL_NAME=gpt-4o-mini
```

feat: add OPENAI_MODEL_NAME environment variable for configurable OpenAI model

---

keep/api/core/db.py
keep/api/routes/alerts.py

Updated `get_error_alerts` to return a list of `AlertRaw` objects instead of an integer and added a query limit for better control. Adjusted default handling in `alerts.py` to ensure `event` defaults to an empty dictionary if `raw_alert` is missing.
Closes #4406

fix: Refactor error alert retrieval and improve default handling

---

keep/providers/uptimekuma_provider/uptimekuma_provider.py

Refactored the method to accumulate and return a list of AlertDto objects instead of a single alert. This ensures proper handling of multiple heartbeats and streamlines data processing. Also moved the `api.disconnect()` call to occur after processing all heartbeats.
Closes #4412

fix: Refactor heartbeat handling to return a list of alerts

---

keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-action-tray.tsx

Closes #3833 
Aligned the icons for alert actions on Incident page as per the expected behavior.
Screenshot after changes:

fix: alignment of alert actions on incident page

---

keep-ui/app/(keep)/incidents/[id]/enrichments/EnrichmentEditableField.tsx
keep-ui/app/(keep)/incidents/[id]/enrichments/EnrichmentEditableForm.tsx
keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
keep/api/core/db.py
keep/api/models/action_type.py
keep/api/models/alert.py
keep/api/models/db/incident.py
keep/api/models/incident.py
keep/api/routes/incidents.py

Introduced editable enrichments for incidents with UI components and API endpoints. Users can now add, edit, or remove enrichments dynamically, with changes propagated to the database and frontend in real-time.
Closes #3552
https://github.com/user-attachments/assets/92802893-31a6-4a9b-9c2e-d212854ece03

feat: Add support for incident enrichment and un-enrichment

---

keep-ui/app/(keep)/incidents/[id]/enrichments/EnrichmentEditableField.tsx
keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
keep/api/routes/incidents.py

Introduce support for `children` in `EnrichmentEditableField` and consolidate repetitive logic for environments and repositories into reusable components. Update backend enrichment to leverage `UUIDType` processing and include database session where required.
Closes #4536

fix: Update backend enrichment to leverage `UUIDType` processing

---

keep/api/logging.py

Closes #4095
📑 Description
Replaced standard FileHandler with RotatingFileHandler to implement automatic log rotation, setting a 10MB maximum file size and keeping 5 backup files. This prevents logs from growing indefinitely while preserving recent logging history.
✅ Checks
My pull request adheres to the code style of this project
All the tests have passed

feat(logging.py): added RotatingFileHandler settings for log file rollout 

---

ee/identitymanager/identity_managers/keycloak/keycloak_authverifier.py
ee/identitymanager/identity_managers/keycloak/keycloak_identitymanager.py
pyproject.toml

close https://github.com/keephq/keep/issues/4563

fix: keycloak verify bug

---

keep/api/tasks/process_event_task.py

Enhanced the function to support single AlertDto objects alongside dict or list inputs. Adjusted the conversion logic to properly wrap non-list inputs into a list for processing.
Closes #4583

fix: Update __save_error_alerts to handle single AlertDto input

---

keep/api/core/db.py
keep/api/core/tenant_configuration.py

Change `get_tenants_configurations` return type to `dict` and ensure tenant configurations are safely updated during reload. Added a warning log for cases where no configurations are found to improve debugging.
Closes #4585

fix: Refactor tenant configurations handling for better robustness

---

keep/rulesengine/rulesengine.py

Add retry logic to manage race conditions caused by StaleDataError during incident updates. Ensures consistent database state by rolling back and retrying up to 3 times if a conflict occurs. Logs informative messages for better traceability of retries.
Closes #4587

fix: Handle race conditions when updating incidents in database

---

keep/functions/__init__.py

Closes #4591
This PR modifies the `index()` utility function to automatically convert string indices (e.g., `"0"`) to integers, preventing `TypeError: list indices must be integers or slices, not str` errors that occurred when indices were passed as strings.
```python
def index(iterable, index) -> any:
if isinstance(index, str) and index.isdigit():  # Safely convert string to int
index = int(index)
return iterable[index]

fix(utils): convert string indices to int in index() function to prevent TypeError

---

keep/parser/parser.py
keep/providers/newrelic_provider/newrelic_provider.py
keep/workflowmanager/workflowmanager.py
keep/workflowmanager/workflowscheduler.py

Updated the exception handling across various modules to use `logger.warning` instead of `logger.exception` or `logger.error`, providing better context with `exc_info` and additional metadata. This improves the clarity and debugging capabilities of the logged errors without being overly verbose.
Closes #4589

fix: Replace some workflows exception logging with warning and include context

---

keep/providers/mailgun_provider/mailgun_provider.py

Added more context to log messages, including "from" and "subject" fields. Improved fallback logic for extracting "subject" and message content, ensuring better event data processing.
Closes #4601

fix: Enhance logging and event handling in Mailgun provider

---

keep/api/core/alerts.py
keep/api/core/cel_to_sql/properties_mapper.py
keep/api/core/cel_to_sql/sql_providers/base.py
keep/api/core/cel_to_sql/sql_providers/mysql.py
keep/api/core/cel_to_sql/sql_providers/postgresql.py
keep/api/core/cel_to_sql/sql_providers/sqlite.py
keep/api/core/incidents.py
tests/cel_to_sql/cel-to-sql-test-cases.json
tests/cel_to_sql/test_cel_to_sql.py

Closes #4432 
- Add mechanism that will detect data type of being filtered field and perform conversion depending on dealect
- Add UUID data type support by SQLite, MySQL, PostgreSQL in CEL-to-SQL translator
- Make id (alert id) and incident.id be UUID during alert queries
- Make id (incident id) be UUID during incident queries
- Support dashed or HEX types of UUID in CEL

fix: Incident field cant be queried

---

keep/api/core/db.py

Added StaleDataError to the list of exceptions retried by `retry_on_db_error`. This ensures better resilience in scenarios where stale data issues occur during database operations.
Closes #4637

fix: Enhance DB retry logic to handle StaleDataError

---

keep/api/bl/enrichments_bl.py
keep/providers/base/base_provider.py

Added checks to confirm the presence of `_enrichments` and `disposable_enrichments` before applying them in the alert enrichment process. Also updated the enrichment logic to prevent saving instance-level enrichments for Elastic environments.
Closes #4342

fix: Skip instance-level enrichment for elastic. Ensure enrichments are applied conditionally

---

docs/providers/documentation/teams-provider.mdx
docs/snippets/providers/teams-snippet-autogenerated.mdx
examples/workflows/keep-teams-adaptive-cards-with-mentions.yaml
examples/workflows/keep-teams-adaptive-cards.yaml
keep/providers/teams_provider/teams_provider.py
tests/test_teams_provider.py

Closes #3599
Add support for user mentions in Adaptive Cards for Teams notifications.
https://github.com/user-attachments/assets/4c5d349f-b201-4cfd-87fd-b20896f7ca24

feat: add support for user mentions in Adaptive Cards for Teams notifications

---

keep/api/core/db.py
keep/api/models/db/migrations/versions/2025-05-06-13-09_7b687c555318.py
tests/test_incidents.py

fix: Replace alerts_count calculation with subquery and add recalculation migration

---

keep-ui/entities/workflows/lib/__tests__/parser.test.ts
keep-ui/entities/workflows/lib/parser.ts
keep-ui/entities/workflows/lib/yaml-utils.ts
keep-ui/entities/workflows/model/schema.ts
keep-ui/entities/workflows/model/yaml.schema.ts
keep-ui/entities/workflows/model/yaml.types.ts
keep-ui/entities/workflows/ui/WorkflowInputFields.tsx
keep-ui/features/workflows/manual-run-workflow/ui/manual-run-workflow-modal.tsx
keep-ui/utils/hooks/useWorkflowRun.ts
keep-ui/widgets/workflow-builder/__tests__/workflow-builder.test.tsx

Closes #4747
https://github.com/user-attachments/assets/348c231c-95b5-4616-991e-7c964722f799
https://github.com/user-attachments/assets/0ca7b45d-b8f3-489b-9ea2-9bf7df75229f

fix: disappearing workflow inputs in UI builder

---

keep-ui/app/(keep)/workflows/[workflow_id]/workflow-overview.tsx
keep-ui/app/(keep)/workflows/workflow-graph.tsx
keep-ui/app/(keep)/workflows/workflow-utils.ts

Closes #4778 
Problem: if workflow executed in 0s, graph will not show it as success.
Fix: return 0.01 instead of 0.
Long term we might want to change seconds to milliseconds or something like that.

fix: use 0.01 for 0s executions and use log scale in wf graphs

---

keep/api/models/db/migrations/versions/2025-05-06-13-09_7b687c555318.py
keep/api/models/db/migrations/versions/2025-05-12-17-49_c2f78c69e9cf.py

fix: Fixed recalculate alerts_count for incidents migration

---

keep-ui/app/(keep)/dashboard/widget-types/preset/widget-alerts-table.tsx
keep-ui/shared/lib/__tests__/object-utils.test.ts
keep-ui/shared/lib/object-utils.ts
keep-ui/widgets/alerts-table/lib/alert-table-utils.tsx

Fixes #4794 - Adds support for nested fields in dashboard widgets by properly traversing object paths. Related to an earlier (closed) PR: #4795, that i inadvertently broke with a force-push/rebase

fix: handle nested object fields in alerts table widget

---

keep-ui/shared/api/workflows.ts
keep/api/core/workflows.py
keep/api/routes/workflows.py
keep/workflowmanager/workflowstore.py
tests/test_workflow_execution.py

Closes #4804 
The problem:
`get_workflows_with_last_executions_v2` return list of same execution N times instead of N correct executions.
Example response from /workflows/query
```
...
"last_executions": [
{
"status": "success",
"execution_time": 0,
"started": "2025-05-19T10:40:43"
},
{
"status": "success",
"execution_time": 0,
"started": "2025-05-19T10:40:43"
},
{
"status": "success",
"execution_time": 0,
"started": "2025-05-19T10:40:43"
},
...
],
```
The cause:
We already do an outerjoin with latest executions in `__build_base_query`:
```
.outerjoin(
latest_executions_subquery_cte,
and_(
Workflow.id == latest_executions_subquery_cte.c.workflow_id,
latest_executions_subquery_cte.c.row_num <= fetch_last_executions,
),
)
```
and then again in `build_workflows_query`
I removed the second …

fix: last executions in get_all_workflows_with_last_execution

---

examples/workflows/consts_and_dict.yml
keep-ui/entities/workflows/lib/__tests__/parseWorkflowYamlToJSON.test.ts
keep-ui/entities/workflows/model/schema.ts
keep-ui/entities/workflows/model/yaml.schema.ts
keep/api/routes/workflows.py

fix: workflow `consts` could be of many types

---

keep-ui/app/(keep)/incidents/[id]/alerts/ALERT_SIDEBAR_INTEGRATION.md
keep-ui/app/(keep)/incidents/[id]/alerts/__tests__/incident-alerts-sidebar.test.tsx
keep-ui/app/(keep)/incidents/[id]/alerts/__tests__/incident-alerts.test.tsx
keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
keep-ui/docs/incident-alerts/ALERT_SIDEBAR_INTEGRATION.md
keep-ui/docs/incident-alerts/CI_CD_FIXES.md
keep-ui/features/alerts/alert-detail-sidebar/ui/alert-sidebar.tsx

close https://github.com/keephq/keep/issues/4789
https://github.com/user-attachments/assets/e5a726bb-c130-4a0f-aff1-7ae8ce73b22b
Initially, `ViewAlertModal` was replaced with `AlertSidebar` in `incident-alerts.tsx` to provide a consistent alert viewing experience when clicking on alert rows. New state variables, `selectedAlert` and `isSidebarOpen`, were introduced to manage the sidebar's visibility and content. A new test file, `incident-alerts-sidebar.test.tsx`, was created to cover this functionality.
Following feedback, the implementation was refined to support both `ViewAlertModal` and `AlertSidebar`. The `ViewAlertModal` was re-enabled to open via the "View" button in the action tray, while `AlertSidebar` remains tied to alert row clicks, offering dual viewing options.
A bug causing …

feat(ui): add alert sidebar to incident table

---

keep/api/core/db.py
keep/api/core/workflows.py
pyproject.toml
tests/test_workflowstore.py

fix: get_all_workflows_with_last_execution shouldn't return dummy workflows

---

keep/api/core/dependencies.py
keep/identitymanager/authverifierbase.py
keep/identitymanager/identity_managers/oauth2proxy/oauth2proxy_authverifier.py

fix: bug authentication errors hard to investigate without extra data in logs

---

keep-ui/features/filter/facet-value.tsx
keep-ui/features/filter/facet.tsx
keep-ui/features/filter/pagination.tsx
keep-ui/features/filter/store/__tests__/facets-store.test.ts
keep-ui/features/filter/store/create-facets-store.ts
keep-ui/features/incidents/incident-list/ui/incident-list.tsx
keep-ui/features/incidents/incident-list/ui/incidents-table.tsx

Closes #5055
- Move toggle/selectOne/selectAll functions to store from Facet component
- Write unit-tests for toggle/selectOne/selectAll in store
- Fix pagination bug on incidents

fix: Fix bug on incidents pagination

---

keep/providers/python_provider/python_provider.py
pyproject.toml

close https://github.com/keephq/keep/issues/5078

feat: support classes

---

docs/snippets/providers/base-snippet-autogenerated.mdx
docs/snippets/providers/console-snippet-autogenerated.mdx
docs/snippets/providers/openshift-snippet-autogenerated.mdx
docs/snippets/providers/slack-snippet-autogenerated.mdx
examples/workflows/openshift_basic.yml
examples/workflows/openshift_monitoring_and_remediation.yml
examples/workflows/openshift_pod_restart.yml
keep/providers/openshift_provider/openshift_provider.py

feat: Improve OpenShift provider connection validation using REST API

---

keep/rulesengine/rulesengine.py
pyproject.toml
tests/test_alert_evaluation.py

close https://github.com/keephq/keep/issues/5107

fix: co-int/str for CELs

---

keep/api/core/alerts.py
keep/api/models/alert.py
keep/api/tasks/process_event_task.py
keep/api/utils/enrichment_helpers.py
keep/rulesengine/rulesengine.py
tests/test_counting.py
tests/test_counting_integration.py
tests/test_rules_engine.py

fix: correlation rule threshold counts already resolved alerts

---

keep/api/alert_deduplicator/alert_deduplicator.py
tests/deduplication/test_deduplications.py

Closes #5131 
For an alert to be considered for full deduplication, it's hash should match with the hash of the last seen alert of the same fingerprint. When prometheus sends multiple notifications for the same alert, there is a possibility for the field order to change. When this happens, the hash that gets generated for the alert with changed field order doesn't match with the one that has the original field order. This results in new alert not being considered for full deduplication.
I have updated the code to sort the dictionary fields before computing the hash in order to get consistent hash values for the alerts with out of order fields.

fix: Sort dict keys before generating the hash

---

docs/snippets/providers/zabbix-snippet-autogenerated.mdx
keep/providers/zabbix_provider/zabbix_provider.py

Closes #5139 
Keep uses a severity map to translate zabbix severity to Keep severity. Currently it references zabbix severities using names. When the severity names are updated in zabbix, keep is unable to map the new names correctly. Hence, it classifies the alerts with changed severities as INFO level alerts. 
Solution: Add support for integer severities to Zabbix provider.
Also, updated the change_severity method to accept integers in addition to severity names for better usability.

fix: Use integer severities for zabbix provider

---

docs/snippets/providers/http-snippet-autogenerated.mdx
docs/snippets/providers/pagerduty-snippet-autogenerated.mdx
examples/workflows/pagerduty.yml
keep/providers/pagerduty_provider/pagerduty_provider.py

Closes #5242
Be able to override routing_key in workflow
Currently, the only way to send to multiples PagerDuty routing_key (integration key) is to have one PagerDuty provider per routing_key.
And the issue is, you cannot use variable in workflow provider property (will open a different issue on this)
Use case is the following:
We have multiples customer platform/environment and we have one PagerDuty service per each.
Sadly, when you create PagerDuty event thru their API, you cannot specify service_id.
The other solution would be to directly incident rather than event but incident would be automatically resolve after x hours and there's not way extend it.

feat: pagerduty provider override routing key in workflow #5242

---

docs/deployment/configuration.mdx
docs/overview/maintenance-windows.mdx
keep/api/api.py
keep/api/arq_worker.py
keep/api/bl/maintenance_windows_bl.py
keep/api/consts.py
keep/api/core/db.py
keep/api/models/action_type.py
keep/api/models/alert.py
keep/api/tasks/process_event_task.py
keep/api/tasks/process_watcher_task.py
keep/rulesengine/rulesengine.py
tests/conftest.py
tests/test_incidents.py
tests/test_maintenance_windows_bl.py

Close #5257
A new strategy to handle alerts which match with the Maintenance Window rules has been implemented. 
The main mechanism consists of running a Watcher to check periodically whether the alerts match with the rules or not.
This watcher has been implemented to Work in a distribute environment (under Redis) as well as in standalone, relying on Create Task of asyncio. 
In general terms, the changes regarding the strategy are:
- Introduce a new status, "Maintenance" to follow the evolve of alerts in Maintenance Windows.
- Introduce a new Event field, "Previous status", to save the status before the Maintenance set.
- Inhibit the Workflow execution and Incident creation if we are facing a Maintenance alert.
- Check periodically if the alerts in Maintenance status continue or not under …

feat: maint windows

---

keep/api/bl/dismissal_expiry_bl.py
keep/api/models/action_type.py
keep/api/tasks/process_watcher_task.py
pyproject.toml
tests/test_dismissal_expiry_bug.py
tests/test_maintenance_windows_bl.py

closes #5047 
Fixes #5047 - Alerts with expired dismissUntil were not automatically becoming visible in search filters, causing confusion for users when temporarily dismissed alerts would remain hidden indefinitely.
The bug existed because:
Static enrichments: dismissed and dismissUntil are stored as enrichments in the database
No background processing: There was no mechanism to automatically clear expired dismissals
Stale filter results: Search filters (sidebar "Not dismissed", CEL expressions like dismissed == false) would continue showing old dismissal state
AlertDto validation: While AlertDto constructor correctly handles expiry logic, search filters operate on stored enrichment data
✅ Background Watcher Implementation
Added a new dismissal expiry watcher that integrates with the …

fix: dismiss until

---

keep/api/config.py

Closes #5280
Extension on https://github.com/keephq/keep/pull/5252
Bootstrap the default single tenant on when we are using onelogin as an identity provider, but we do not want a default user created

fix: Bootstrap the default single tenant on when we are using onelogin as an IDP

---

docs/snippets/providers/fluxcd-snippet-autogenerated.mdx
keep/providers/fluxcd_provider/fluxcd_provider.py

Closes #5307
Adds `reconcile` action for FluxCD.
###
Workflow example
```yaml
actions:
- name: flux-action
provider:
type: fluxcd
config: "{{ providers.flux }}"
with:
action: reconcile
kind: HelmRelease
name: my-app
namespace: my-namespace
```

feat(provider): add reconcile functionality to fluxcd provider

---

keep-ui/app/(keep)/providers/provider-form.tsx
keep-ui/shared/lib/encodings.ts

Closes #5322
Added a helper function to generate a random string of 128 characters compliant with RFC7636: https://datatracker.ietf.org/doc/html/rfc7636
- [ x] My pull request adheres to the code style of this project

fix: added a new pkce string generator and use that in oauth handshake

---

keep/providers/webhook_provider/webhook_provider.py
tests/e2e_tests/test_end_to_end.py

Closes https://github.com/keephq/keep/issues/5319

fix: Webhook provider uses dummy payload for validation

---

keep/api/core/alerts.py
tests/test_search_alerts.py

Closes #5293
Filtering by incident.id==null in the Feed, we may have some of alert with incidents, this happened if there was an alert with more than one incident, where one of them was different to Firing.
I've change the Incident.status == Firing OuterJoin by a subquery. This subquery allows us to make null the OuterJoin in case of there is an alert with one or more Incidents. Hence, the filter incident.id == / != null will work nice.

fix: Searching by incident.id in CEL filter

---

keep/api/bl/maintenance_windows_bl.py
keep/api/core/db.py
tests/test_maintenance_windows_bl.py

Closes #5321
With this new PR I've introduced some improvements in Maintenance windows:
-  The alerts are free if the finalization hour is bigger than the current one.
-  Once the maintenance window is over, the alerts will only trigger the WF and Incidents by its fingerprint.
-  In order to track, the alerts will have a new field including the ID of the window.

feat: Maintenance windows improvements
