keephq/keep

- keep/action/action.py
- keep/cli/cli.py
- keep/exceptions/provider_notify_exception.py
- keep/providers/slack_provider/slack_provider.py
> Feature: URL Shortener

- examples/alerts/db_disk_space.yml
- keep/exceptions/provider_exception.py
- keep/providers/base/base_provider.py
- keep/providers/console_provider/console_provider.py
- keep/providers/newrelic_provider/newrelic_provider.py
- keep/providers/slack_provider/slack_provider.py
- keep/providers/snowflake_provider/snowflake_provider.py
> feat: new relic provider and a few bugfixes

- examples/alerts/db_disk_space.yml
- keep/alertmanager/alertmanager.py
- keep/cli/cli.py
- keep/parser/parser.py
- keep/providers/base/base_provider.py
- keep/providers/console_provider/console_provider.py
- keep/providers/elastic_provider/elastic_provider.py
- keep/providers/mock_provider/mock_provider.py
- keep/providers/models/provider_config.py
- keep/providers/providers_factory.py
- keep/providers/sentry_provider/sentry_provider.py
- keep/providers/slack_provider/slack_provider.py
- keep/providers/snowflake_provider/snowflake_provider.py
- keep/providers/ssh_provider/ssh_provider.py
> feat(cli): --providers-file

- docs/docs/providers/what-is-a-provider.md
> Docs: What is a Provider - typo/grammar

- README.md
> fix(typo): slack webhook in README

- docs/docs/providers/documentation/http.md
- examples/alerts/simple_http_request_ntfy.yml
- keep/alert/alert.py
- keep/parser/parser.py
- keep/providers/http_provider/http_provider.py
> 48 missing ntfy as notification provider

- keep/providers/http_provider/http_provider.py
Sorry if this is being pedantic, I was going through the code and noticed this small typo! 
I thought I would send you a small PR :)
Awesome work by the way!
> Fix a small typo

- README.md
> docs(readme): intro improvements

- .github/workflows/lint-pr.yml
- docs/docs/providers/documentation/pagerduty.md
- examples/alerts/db_disk_space_pagerduty.yml
- keep/providers/pagerduty_provider/pagerduty_provider.py
Closes #59 
PagerDuty provider that implements both the events and incidents APIs.
> feat(provider): pagerduty provider

- docs/docs/providers/documentation/telegram.md
- examples/alerts/db_disk_space_telegram.yml
- keep/action/action.py
- keep/contextmanager/contextmanager.py
- keep/providers/telegram_provider/telegram_provider.py
- pyproject.toml
> feat: add telegram provider

- README.md
> docs: updated Readme

- docs/docs/providers/documentation/slack.md
> docs: slack provider document updated

- docs/docs/providers/documentation/slack.md
> feat: slack doc

- keep/api/routes/alertsfiles.py
- keep/cli/cli.py
- keep/cli/click_extensions.py
- keep/conditions/threshold_condition.py
- keep/contextmanager/contextmanager.py
- keep/functions/__init__.py
- keep/iohandler/iohandler.py
- keep/providers/console_provider/console_provider.py
- keep/providers/discord_provider/discord_provider.py
- keep/providers/github_provider/github_provider.py
- keep/providers/jira_provider/jira_provider.py
- keep/providers/newrelic_provider/newrelic_provider.py
- keep/providers/opsgenie_provider/opsgenie_provider.py
- keep/providers/pagerduty_provider/pagerduty_provider.py
- keep/providers/psql_provider/psql_provider.py
- keep/providers/pushover_provider/pushover_provider.py
- keep/providers/slack_provider/slack_provider.py
- keep/providers/trello_provider/trello_provider.py
- keep/providers/zenduty_provider/zenduty_provider.py
This PR is to fix some typos, update python 3 language requirements and simplify some code.
- [Y ] My pull request adheres to the code style of this project
- [ Y] My code requires changes to the documentation
- [Y ] I have updated the documentation as required
- [ Y] All the tests have passed
> style: Language updates and fixes

- keep/conditions/threshold_condition.py
close https://github.com/keephq/keep/issues/116
> fix: fixing wrong type checking

- keep/action/action.py
https://getkeep.slack.com/archives/C04PT44MATS/p1682185551375159
> fix: solving condition parsing bug (see slack link in issue body)

- docs/docs/023_conditions/02-threshold.md
- docs/docs/023_conditions/03-assert.md
- docs/docs/023_conditions/04-stddev.md
- examples/alerts/db_disk_space.yml
- examples/alerts/keep_semantic_alert_example_datadog.yml
- examples/alerts/new_github_stars.yml
- examples/alerts/raw_sql_query_datetime.yml
- examples/alerts/simple_http_request_ntfy.yml
- examples/alerts/trello_new_card_alert.yml
- keep/action/action.py
Closes #105
If a condition name is missing, the new implementation will throw an exception at the time of condition initialisation: "Condition must have a name".
Without condition name:
With condition name:
@talboren As discussed, I was trying to optimise the code to use only one pass over the conditions list, however, the list of initialised conditions is being used on line 113 to create a string of all conditions. We can discuss on how to optimise this without breaking the existing implementation.
cc: @shahargl
> fix: Raise exception if condition name is missing

- docs/docs/022_providers/documentation/trello.md
- keep/providers/trello_provider/trello_provider.py
Closes # 
Trello provider docs added
> docs: trello docs added

- docs/docs/022_providers/documentation/jira.md
- keep/providers/jira_provider/jira_provider.py
Closes # 
jira provider docs added
> docs: jira docs added

- keep/functions/__init__.py
- pyproject.toml
- tests/test_functions.py
add pytest to pyproject.toml dev deps
functions: add typing to diff function
I tried to run the python tests, but noticed that pytest wasn't installed, [even though the import was used in the sanity tests](https://github.com/keephq/keep/blob/b07a4da58d5038b4745e9752d0ff14e67d65efd7/tests/test_sanity.py#L6).
For fun, I also added some tests around the diff function.  Pointing out a couple of behaviors that might be surprising.  I didn't change any code behavior.
> test: functions.diff

- keep/functions/__init__.py
This PR adds a new function `keep.encode()` which can be useful in case of adding urls to slack notifications, which needs to be encoded.
Usage:
```
keep.encode("{{ steps.myalert.provider_parameters.query}}")
```
> feat: add keep.encode() to functions

- README.md
Closes #77 
Added alert definition as requested in issue #77 
- [] All the tests have passed
> docs: Keep issue #77

- keep/parser/parser.py
- tests/test_parser.py
Added some unit tests around loading providers from a file
> test: add tests for loading providers by file

- docs/overview/introduction.mdx
Fix typo in the webhook integration text (Overview - Introduction).
N/A
> docs: fix typo in Introduction

- keep-ui/app/alerts/alert-menu.tsx
closes https://github.com/keephq/keep/issues/349
> fix: alert item dropdown is cropped

- keep-ui/app/navbar-inner.tsx
- keep-ui/app/providers/layout.tsx
closes https://github.com/keephq/keep/issues/354
> fix: hover issue web icons

- keep-ui/app/providers/provider-form.tsx
- keep/providers/grafana_provider/grafana_provider.py
- keep/providers/kafka_provider/kafka_provider.py
closes https://github.com/keephq/keep/issues/394
> feat: hide sensitive fields by default

- keep-ui/app/providers/providers-tiles.css
- keep-ui/app/providers/providers-tiles.tsx
- keep-ui/package-lock.json
UI update
Thanks for creating this pull request 🤗
Closes  #412 
#412 : Providers page overflow on both medium and smaller screens 
-->
Small screen before
Small screen after
Medium screen after
Small screen sidepanel
9e52f96-ddce-4ff7-a508-58fb05387758)
> fix(ui): Small and medium screen responsiveness

- keep-ui/app/providers/provider-form.tsx
- keep-ui/package-lock.json
- keep-ui/package.json
- keep/providers/grafana_provider/grafana_provider.py
- keep/providers/models/provider_config.py
updated tremor version as well
> fix: grafana webhook, grafana scopes and secret inputs redundant code

- README.md
> chore: update README.md with twilio

- docs/providers/documentation/new-relic-provider.mdx
Added docs for newrelic provider
> docs: new relic provider

- .gitignore
- keep/cli/cli.py
close https://github.com/keephq/keep/issues/552
> feat: add auth login oauth from cli

- keep/api/routes/workflows.py
- keep/providers/providers_factory.py
close https://github.com/keephq/keep/issues/542
> fix: consider providers without conf as installed

- keep/api/models/db/alert.py
Alert and AlertEnrichment relationship fixed.
Relationship is one-to-many, with AlertEnrichment being the "one" side and Alert being the "many" side.
There can be multiple Alerts with the same fingerprint but only one enrichment for that fingerprint.
> fix: Alert and AlertEnrichment relationship

- keep/providers/opsgenie_provider/opsgenie_provider.py
close https://github.com/keephq/keep/issues/614
> feat: opsgenie better handling errors

- chart/keep/templates/delete-secret-job.yaml
- chart/keep/templates/keep-backend.yaml
- chart/keep/values.yaml
close https://github.com/keephq/keep/issues/645
> feat: take k8s namespace from values

- keep/providers/mattermost_provider/mattermost_provider.py
Closes # 
removed mattermost channel option from backend, as mattermost returns 400 if it is added to the payload
> fix: removed-mattermost-channel-payload

- README.md
- start.sh
> feat: New start script

- keep/providers/jira_provider/jira_provider.py
- keep/providers/jiraonprem_provider/jiraonprem_provider.py
closes #699 
Ability to set labels or custom fields like Component/s when creating Jira ticket
> feat: Ability to set labels or custom fields like Component/s when creating Jira ticket

- keep/providers/postgres_provider/postgres_provider.py
> feat: Add scopes to Postgres provider

- keep-ui/app/alerts/models.tsx
- keep/parser/parser.py
- keep/workflowmanager/workflowmanager.py
- keep/workflowmanager/workflowscheduler.py
+ remove a few redundant duplicate logs
> fix(ui): remove message from known keys

- keep/secretmanager/vaultsecretmanager.py
- Adding K8S auth method to vault to allow authentication with k8s service account.
> feat(secretmanager): add k8s auth method to vault

- keep-ui/app/alerts/alert-table-tab-panel.tsx
- keep-ui/utils/hooks/useAlerts.ts
- change `sorted` to `toSorted` to maintain data immutability
- spread existing alerts in the new array
> fix: flashing alerts from pusher

- keep-ui/utils/hooks/useAlerts.ts
- use `Map` to use only the last alerts
- change spread order
> fix: Later Alerts Didn't Overwrite Earlier Ones

- keep-ui/app/alerts/alert-columns-select.tsx
- keep-ui/app/alerts/alert-history.tsx
- keep-ui/app/alerts/alert-menu.tsx
- keep-ui/app/alerts/alert-table-headers.tsx
- keep-ui/app/alerts/alert-table-tab-panel.tsx
- keep-ui/app/alerts/alert-table-utils.tsx
- keep-ui/app/alerts/alert-table.tsx
- keep-ui/package-lock.json
- keep-ui/package.json
- keep-ui/utils/hooks/useLocalStorage.ts
Some suggestions to your PR. I liked the direction you took, but some of the changes felt like the tail wagging the dog. Incorporated some of my previous OS work (`useLocalStorage`) to help out
> chore(ui): Column Visibility

- keep-ui/app/dark-mode-toggle.tsx
- keep-ui/app/navbar-inner.tsx
- keep-ui/app/navbar.tsx
- keep/providers/sentry_provider/sentry_provider.py
- also a small bugfix in sentry provider to allow events coming in from internal integration
> feat(ui): simple dark mode

- keep-ui/app/alerts/alert-extra-payload.tsx
- keep-ui/app/alerts/alert-table-headers.tsx
- keep-ui/app/alerts/alert-table-utils.tsx
- keep-ui/app/alerts/alert-table.tsx
- add state for handling column sizes
- add minimum sizes to column definitions
- add column resizing logic
> feat(ui): Column Width Resizing

- keep/providers/jiraonprem_provider/jiraonprem_provider.py
- keep/providers/sentry_provider/sentry_provider.py
- Also fix(provider): jira on prem to support priority set
> fix(provider): sentry to keep exception details as well

- keep-ui/app/alerts/alert-menu.tsx
> fix(ui): self-assign was hidden when assigned

- keep-ui/app/layout.tsx
- keep-ui/components/navbar/Menu.tsx
- keep-ui/components/navbar/MinimizeMenuButton.tsx
- keep-ui/components/navbar/Navbar.tsx
- create `MinimizeMenuButton` 
- add Tailwind and CSS magic
- allow hiding menu on large screens
> feat(ui): Allow minimization of `<Navbar />`

- keep/api/routes/alerts.py
- keep/parser/parser.py
- keep/providers/grafana_provider/grafana_provider.py
- keep/providers/squadcast_provider/squadcast_provider.py
- keep/providers/websocket_provider/websocket_provider.py
- keep/workflowmanager/workflowmanager.py
fix deprecated `self.logger.warn` and some typos in workflowmanager.
> fix: deprecated log and some typos

- keep-ui/app/alerts/alert-history.tsx
- keep-ui/app/alerts/alert-table-utils.tsx
- keep-ui/app/loading.tsx
- keep-ui/app/providers/provider-row.tsx
- keep-ui/app/workflows/builder/alert.tsx
- keep-ui/app/workflows/builder/builder-validators.tsx
- keep-ui/app/workflows/builder/utils.tsx
- keep/api/core/db.py
- keep/api/models/db/workflow.py
* alert menu to be static in ui
* fix small issue with keep.svg in loader
> fix(api): mysql query when filtering alerts in workflows

- docs/mint.json
- keep/cli/cli.py
added help message for alert get command.
> fix(cli): add help message to alert get cmd

- keep/api/models/alert.py
close https://github.com/keephq/keep/pull/914
> feat: normalize fingerprint

- keep/cli/cli.py
if no alerts found print `No alerts found.` and return instead of printing empty table
> feat(cli): handle if no alerts found

- keep-ui/app/mapping/create-new-mapping.tsx
Closes #924 
added priority input for mapping ui
> feat(ui): add priority input to mapping ui

- keep-ui/app/workflows/workflows.client.tsx
Closes #934 
Allow users to upload multiple files at once.
> feat(ui): allow multiple workflow file upload

- docs/providers/documentation/squadcast-provider.mdx
- keep/providers/squadcast_provider/squadcast_provider.py
added additional_json field to utilize it on squadcast
> chore(providers): add new field for squadcast provider

- docs/cli/commands/mappings-create.mdx
- keep/cli/cli.py
Closes #946 
updated the type of the priority flag to check the range of the priority
> chore(cli): update mappings priority flag type

- keep/providers/cloudwatch_provider/cloudwatch_provider.py
Closes #951 
fix cloudwatch provider scope
> fix(providers): fix cloudwatch provider scope

- docs/deployment/ecs.mdx
> feat(docs): update ecs docs

- keep/providers/splunk_provider/splunk_provider.py
> fix: Update splunk_provider.py description typo

- keep/providers/cloudwatch_provider/cloudwatch_provider.py
When alarm action already exists in the alarm the provider was trying to add it as well then it was throwing exception which causes provider to continue and skip subscribe loop in the end provider was saying webhook installed successfully but it wasn't really subscribing to sns topic. This PR aims to solve that problem.
> fix(providers): check if provided sns_topic already exists or not

- docs/cli/installation.mdx
- keep/providers/cloudwatch_provider/cloudwatch_provider.py
> feat(doc): Update Keep CLI installation information requiring Python 3.11

- docs/workflows/functions/last.mdx
- docs/workflows/functions/lowercase.mdx
- docs/workflows/functions/uppercase.mdx
- keep/functions/__init__.py
- tests/test_functions.py
added new functions might be handy:
- uppercase
- lowercase
- last
> feat: add new functions

- keep-ui/package-lock.json
- keep-ui/package.json
> chore(deps): update posthog to 1.116.2

- keep-ui/app/workflows/models.tsx
- keep-ui/app/workflows/workflow-tile.tsx
- keep/api/routes/workflows.py
Closes #982 
Display workflow last update time in workflows page.
> feat(ui): display workflow last update time in workflows page

- keep/providers/grafana_provider/grafana_provider.py
close https://github.com/keephq/keep/issues/1059
> fix: grafana

- keep/providers/linearb_provider/linearb_provider.py
> fix(provider): linearb to accept issued_at

- keep/providers/cloudwatch_provider/alerts_mock.py
- keep/providers/cloudwatch_provider/cloudwatch_provider.py
- keep/providers/prometheus_provider/alerts_mock.py
> feat: add mocking alert for cloudwatch provider

- keep-ui/app/workflows/builder/builder.tsx
- keep-ui/app/workflows/builder/utils.tsx
- keep/api/routes/workflows.py
- keep/workflowmanager/workflowstore.py
Added name text input to let user to set name for workflow inside the workflow builder.
> feat: added naming option to workflow builder

- examples/workflows/telegram_basic.yml
- keep/providers/telegram_provider/telegram_provider.py
- keep/step/step.py
- tests/test_steps.py
close https://github.com/keephq/keep/issues/1196
> fix: telegram

- docs/development/getting-started.mdx
Closes # 
Fix for the docker compose command
> fix: getting started docker command

- keep/api/models/db/provider.py
In provider table name column is not unique and it is kind of problematic this PR aims to fix that problem.
> fix: updated provider db model to make name unique

- docs/cli/commands/extraction-create.mdx
- docs/cli/commands/extraction-delete.mdx
- docs/cli/commands/extractions-list.mdx
- docs/cli/commands/mappings-create.mdx
- keep/cli/cli.py
Added extraction command to the cli
> feat(cli): add extraction command

- examples/workflows/severity_changed.yml
- keep-ui/app/providers/provider-tile.tsx
- keep-ui/components/navbar/DashboardLinks.tsx
- keep-ui/package-lock.json
- keep-ui/package.json
- keep/api/models/alert.py
- keep/workflowmanager/workflowmanager.py
style: small badge fix for dashboards padding
chore(deps): posthog version
style: truncate provider id
- 	new file:   ../examples/workflows/severity_changed.yml
- 	modified:   ../keep-ui/app/providers/provider-tile.tsx
- 	modified:   ../keep-ui/components/navbar/DashboardLinks.tsx
- 	modified:   ../keep-ui/package-lock.json
- 	modified:   ../keep-ui/package.json
- 	modified:   ../keep/api/models/alert.py
- 	modified:   ../keep/workflowmanager/workflowmanager.py
> feat(workflow): run wf when severity changes

- keep/api/routes/alerts.py
- keep/api/routes/preset.py
- keep/api/tasks/process_event_task.py
Saving alerts from 3rd party providers, relying on duplicator logics.
It's a PR to another PR https://github.com/keephq/keep/pull/1276
> feat: Save alerts from 3rd party providers

- keep/providers/ilert_provider/ilert_provider.py
Closes #1263
Fixed [https://github.com/keephq/keep/issues/1263#issuecomment-2192221024](https://github.com/keephq/keep/issues/1263#issuecomment-2192221024)
> fix: ilert provider

- keep/providers/openobserve_provider/openobserve_provider.py
> fix: openobserver errors

- keep-ui/utils/hooks/useAlerts.ts
close https://github.com/keephq/keep/issues/1305
> fix: presets

- .gitignore
- docs/development/getting-started.mdx
Small note about how to run tests
> docs: how to run tests

- keep/api/models/alert.py
close https://github.com/keephq/keep/issues/1397
> fix: AlertDto validate_last_received problem

- scripts/shoot_alerts_from_dump.py
> Alert shooter

- keep-ui/app/alerts/alert-menu.tsx
close https://github.com/keephq/keep/issues/1395
> fix: alert menu size

- keep/api/core/elastic.py
- keep/searchengine/searchengine.py
- tests/conftest.py
close https://github.com/keephq/keep/issues/1419
> fix: tests

- keep-ui/app/alerts/alert-table.tsx
close https://github.com/keephq/keep/issues/1396
> fix: do not open sidebar on history

- keep-ui/app/settings/webhook-settings.tsx
- keep-ui/utils/fetcher.ts
- keep/api/routes/settings.py
close https://github.com/keephq/keep/issues/1423
> fix: webhook-settings-keep-loading-on-error

- keep-ui/app/workflows/builder/utils.tsx
close https://github.com/keephq/keep/issues/1391
> fix(ui): Workflow builder move the workflow 'if' condition provider nesting

- keep/api/routes/workflows.py
close https://github.com/keephq/keep/issues/1427
> fix: upload workflow

- keep/parser/parser.py
`on_failure` action was not functioning, this PR aims to fix that
> fix(workflows): fixed on_failure action

- keep-ui/app/alerts/ViewAlertModal.css
- keep-ui/app/alerts/ViewAlertModal.tsx
- keep-ui/app/alerts/alerts.tsx
- keep-ui/app/alerts/models.tsx
- keep/api/bl/enrichments.py
- keep/api/models/alert.py
- keep/api/models/db/alert.py
- keep/api/routes/alerts.py
- keep/api/utils/enrichment_helpers.py
Closes #1369  and #1246 
The feature allows user to see Enriched data in Alert Details and reset such fields.
https://github.com/user-attachments/assets/820fb0de-ce61-4da1-accc-16d68223468e
UPD: It now also allows to see ONLY enriched lines
> feat: #1369, #1246 Highlight Enrichments and allow to delete them in Alert Details UI

- keep-ui/app/incidents/incidents-table.tsx
> fix: #1447 incident predictions table long text fix

- keep-ui/app/workflows/mockworkflows.tsx
- keep-ui/app/workflows/workflow-tile.tsx
> chore(ui): handled the trigger button and hover broder on cards

- keep/api/core/elastic.py
- keep/searchengine/searchengine.py
- tests/test_search_alerts.py
closes https://github.com/keephq/keep/issues/1462
> fix: enrichments

- keep-ui/app/workflows/mockworkflows.tsx
- keep-ui/app/workflows/workflow-tile.tsx
fixed the error image fallback issue
> fix: missing trigger icon if image not found

- keep/api/tasks/process_event_task.py
close https://github.com/keephq/keep/issues/1466
> fix(api): `notify_client` not passed to `_handle_event`

- keep-ui/app/alerts/alert-push-alert-to-server-modal.tsx
- keep-ui/app/alerts/alert-table.tsx
- keep-ui/app/alerts/alerts-table-body.tsx
- keep-ui/app/providers/providers.tsx
- keep/api/models/provider.py
- keep/providers/cloudwatch_provider/cloudwatch_provider.py
- keep/providers/grafana_provider/alerts_mock.py
- keep/providers/providers_factory.py
close https://github.com/keephq/keep/issues/1475
> feat: alerts-empty-state-improvements

- examples/workflows/sendgrid_basic.yml
- keep-ui/app/workflows/workflow-run-with-alert-modal.tsx
- keep/api/routes/workflows.py
- keep/providers/sendgrid_provider/sendgrid_provider.py
close https://github.com/keephq/keep/issues/1483
> fix: sendgrid and workflows

- keep/providers/sendgrid_provider/sendgrid_provider.py
close https://github.com/keephq/keep/issues/1484
> fix: sendgrid return value

- keep/api/arq_worker.py
- keep/api/tasks/process_event_task.py
Not sure if it's the best decision, but that's the only way I found to make Arq work :)
> fix: arq by adding an async_process_event

- docs/providers/documentation/sendgrid-provider.mdx
- keep/api/core/db.py
- keep/api/models/provider.py
- keep/api/routes/providers.py
- add service function in api/core/db.py
- add endpoint in api/routes/providers.py
Closes #1249 
/claim #1249
> feat: API endpoint to see how many alerts a provider has sent

- .github/workflows/test-pr-e2e.yml
- examples/workflows/sendgrid_basic.yml
- keep/providers/sendgrid_provider/sendgrid_provider.py
close https://github.com/keephq/keep/issues/1515
> feat: more than one "to"

- docs/development/getting-started.mdx
- keep-ui/.env.local.example
> fix: VS code quickstart

- keep/api/core/elastic.py
close https://github.com/keephq/keep/issues/1520
> fix: patch dismissed

- keep/providers/openobserve_provider/openobserve_provider.py
close https://github.com/keephq/keep/issues/1521
> feat: sort fingerprint fields

- README.md
> fix: remove license badge from README

- docker/Dockerfile.dev.ui
- docs/development/getting-started.mdx
Closes #1524
We have few problems, which new developers may get while following getting started instruction.
> fix: problems with getting started instructions

- keep/api/core/db.py
- keep/workflowmanager/workflowmanager.py
- keep/workflowmanager/workflowscheduler.py
> chore: add more logs to workflows and refresh enrichments

- keep/workflowmanager/workflowmanager.py
> chore(logs): understand why event is skipped in wf execution

- keep/workflowmanager/workflowscheduler.py
> fix(api): remove workflow_execution_id from unnecessary logs

- keep/api/models/db/migrations/versions/2024-08-08-13-55_42098785763c.py
close https://github.com/keephq/keep/issues/1564
> fix: Merging 2 heads

- keep-ui/app/incidents/[id]/incident-alerts.tsx
- keep-ui/app/incidents/[id]/incident.tsx
- keep-ui/app/incidents/incident-pagination.tsx
- keep-ui/app/incidents/model.ts
- keep-ui/utils/hooks/useIncidents.ts
- keep/api/core/db.py
- keep/api/routes/incidents.py
- keep/api/utils/pagination.py
Closes #1472 
The incident details page now has paginated alerts, so when we have a lot of them page still loads fast
> fix: poor performance of incidents detail page

- keep-ui/app/alerts/alert-associate-incident-modal.tsx
> fix(ui): build failing due to #1540 issue that got merged

- keep/api/routes/preset.py
close https://github.com/keephq/keep/issues/1583
> fix: minor issue with update preset

- keep-ui/app/alerts/alert-presets.tsx
close https://github.com/keephq/keep/issues/1586
> fix: mutate tags after creating

- keep/api/core/db.py
close https://github.com/keephq/keep/issues/1590
> fix(db): call `unique()` when getting all presets

- keep/api/core/db_on_start.py
close https://github.com/keephq/keep/issues/1597
> feat: allow provision api key

- keep/api/core/db_on_start.py
close https://github.com/keephq/keep/issues/1602
> fix: keep the api key on secret manager

- keep/api/api.py
- keep/api/arq_worker.py
- keep/api/tasks/healthcheck_task.py
> feat: Healthcheck arq task & disabling background task

- keep-ui/app/ai/ai.tsx
- keep/api/core/db.py
- keep/api/routes/incidents.py
> fix: incident page loading

- keep-ui/app/incidents/[id]/incident-info.tsx
- keep-ui/app/incidents/create-or-update-incident.tsx
- keep-ui/app/incidents/incidents-table.tsx
- keep-ui/app/incidents/model.ts
- keep-ui/app/incidents/predicted-incidents-table.tsx
> fix: Switch UI from using description to user_summary for incidents

- README.md
close https://github.com/keephq/keep/issues/1622
> fix: readme coralogix

- keep/workflowmanager/workflowmanager.py
close https://github.com/keephq/keep/issues/1628
> feat: more logs + debug mode

- keep/api/routes/alerts.py
close https://github.com/keephq/keep/issues/1631
> fix: redis

- keep-ui/app/error.tsx
- keep-ui/app/providers/page.client.tsx
- keep-ui/utils/fetcher.ts
close https://github.com/keephq/keep/issues/1636
> feat: better error handling

- tests/test_workflow_execution.py
close https://github.com/keephq/keep/issues/1639
> fix: add sleep

- STRESS.md
- docs/deployment/stress-testing.mdx
- docs/mint.json
close https://github.com/keephq/keep/issues/1645
> feat: add stress testing

- keep/api/core/db_utils.py
close https://github.com/keephq/keep/issues/1647
> fix: pool size

- tests/test_workflow_execution.py
close https://github.com/keephq/keep/issues/1648
> fix: unit tests

- ee/experimental/incident_utils.py
- keep/api/core/db.py
> fix: use an appropriate function for alert querying

- keep-ui/.gitignore
- keep-ui/app/alerts/alert-change-status-modal.tsx
- keep-ui/app/alerts/alert-dismiss-modal.css
- keep-ui/app/alerts/alert-dismiss-modal.tsx
- keep-ui/components/ui/Select.tsx
close https://github.com/keephq/keep/issues/1493
> fix: dismiss and manual resolve

- keep/api/config.py
- keep/api/core/db_on_start.py
> fix: Migrations in some cases ignore SKIP_DB_CREATION

- keep/api/core/db.py
- keep/api/tasks/process_background_ai_task.py
> fix: Run backend correlation in optimized way

- keep/api/tasks/process_event_task.py
> fix: Retry task only if it's an Arq task

- keep-ui/app/alerts/alert-dismiss-modal.tsx
close https://github.com/keephq/keep/issues/1659
> fix: minor problem with dismiss

- ee/experimental/statistical_utils.py
- keep/api/core/db.py
> fix: clip operation for pmi_matrix added

- keep/api/core/db.py
> fix: PMI saving

- keep-ui/app/providers/providers-tiles.tsx
close https://github.com/keephq/keep/issues/1689
> fix: hide no-config providers

- examples/workflows/http_example.yml
- keep/functions/__init__.py
- keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
close https://github.com/keephq/keep/issues/1690
> feat: allow json in http

- keep-ui/package-lock.json
- keep-ui/package.json
close https://github.com/keephq/keep/issues/1699
> feat: update posthog

- keep/api/api.py
- keep/api/core/db.py
- keep/api/routes/providers.py
- keep/api/tasks/process_event_task.py
- keep/providers/providers_service.py
- tests/conftest.py
close https://github.com/keephq/keep/issues/1661
> feat: provision providers

- keep/iohandler/iohandler.py
close https://github.com/keephq/keep/issues/1715
> fix: allow workflows to use dict

- keep/api/models/db/alert.py
- keep/api/models/db/migrations/versions/2024-08-25-16-40_4ef2c767664c.py
> fix: rule_fingerprint stores not hashed value, so can be bigger than VARCHAR

- keep/providers/openobserve_provider/openobserve_provider.py
close https://github.com/keephq/keep/issues/1741
> feat(provider): open observe improvements

- keep/providers/openobserve_provider/openobserve_provider.py
close https://github.com/keephq/keep/issues/1753
> fix: debug

- keep-ui/components/navbar/AlertsLinks.tsx
- keep/api/api.py
- keep/api/consts.py
- keep/api/routes/preset.py
- keep/api/tasks/process_event_task.py
close https://github.com/keephq/keep/issues/1757
close https://github.com/keephq/keep/issues/1756
close https://github.com/keephq/keep/issues/1755
> fix: multiple fixes

- keep-ui/app/ai/ai.tsx
- keep-ui/app/incidents/create-or-update-incident.tsx
- keep/api/core/db.py
- keep/api/routes/incidents.py
> feat: generating summary using AI for manually created incidents 

- .github/workflows/test-pr.yml
- tests/e2e_tests/docker-compose-e2e-mysql.yml
- tests/e2e_tests/docker-compose-e2e-postgres.yml
close https://github.com/keephq/keep/issues/1760
> feat: e2e impovements

- keep/providers/zabbix_provider/zabbix_provider_script.js
> fix(zabbix): media type response failure

- scripts/docs_generate_api_docs_from_openapi.sh
- scripts/docs_validate_navigation.sh
> fix: Polish docs scripts

- .github/workflows/test-pr-e2e.yml
close https://github.com/keephq/keep/issues/1777
> fix: Disable API docs tests

- examples/workflows/http_example.yml
close https://github.com/keephq/keep/issues/1787
> feat(docs): update typo workflow name

- ee/identitymanager/identity_managers/auth0/auth0_identitymanager.py
- keep-ui/app/settings/auth/users-sidebar.tsx
close https://github.com/keephq/keep/issues/1795
> fix: auth0 create user

- .github/workflows/release.yml
- .github/workflows/test-pr.yml
close https://github.com/keephq/keep/issues/1814
> fix: release workflow naming convention problem

- keep/api/core/db.py
> fix: incident editing functionality

- keep-ui/app/incidents/incidents-table.tsx
- keep-ui/app/incidents/model.ts
- keep/api/core/db.py
- keep/api/models/alert.py
> feat: show grouping value for incidents created by rules

- ee/identitymanager/identity_managers/auth0/auth0_identitymanager.py
- keep-ui/app/settings/auth/users-sidebar.tsx
close https://github.com/keephq/keep/issues/1827
> fix: auth0 update user

- keep-ui/app/settings/settings.client.tsx
close https://github.com/keephq/keep/issues/1842
> fix: minor bug in keycloak UI

- keep-ui/app/incidents/[id]/incident-info.tsx
> feat: show incident rule_fingerprint at detailed page as well

- keep-ui/app/workflows/[workflow_id]/executions.tsx
- keep-ui/app/workflows/[workflow_id]/workflow-execution-table.tsx
- keep-ui/app/workflows/builder/types.tsx
- keep/api/core/db.py
- keep/api/routes/workflows.py
- keep/api/utils/pagination.py
> refactor: add new stat card and number format change

- keep/api/consts.py
- keep/api/routes/alerts.py
- keep/api/tasks/process_event_task.py
close https://github.com/keephq/keep/issues/1852
> feat: add job id

- keep/api/api.py
- keep/api/arq_worker.py
- keep/api/consts.py
- keep/api/routes/alerts.py
close https://github.com/keephq/keep/issues/1855
> fix: make redis great again

- keep/providers/newrelic_provider/newrelic_provider.py
close https://github.com/keephq/keep/issues/1857
> fix: newrelic fix

- keep/providers/newrelic_provider/newrelic_provider.py
close https://github.com/keephq/keep/issues/1860
> fix: new relic

- keep/providers/newrelic_provider/newrelic_provider.py
close https://github.com/keephq/keep/issues/1862
> fix: new relic source

- pyproject.toml
close https://github.com/keephq/keep/issues/1872
> chore(release): 0.24.0 

- keep-ui/app/rules/CorrelationSidebar/AlertsFoundBadge.tsx
- keep-ui/app/rules/CorrelationSidebar/CorrelationForm.tsx
- keep-ui/app/rules/CorrelationSidebar/CorrelationGroups.tsx
- keep-ui/app/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
- keep-ui/app/rules/CorrelationSidebar/CorrelationSubmission.tsx
- keep-ui/app/rules/CorrelationSidebar/RuleFields.tsx
- keep-ui/app/rules/CorrelationSidebar/RuleGroup.tsx
- keep-ui/app/rules/CorrelationSidebar/index.tsx
- keep-ui/app/rules/CorrelationTable.tsx
- keep-ui/utils/hooks/useRules.ts
- keep/api/core/db.py
- keep/api/models/db/migrations/versions/2024-08-26-17-01_1aacee84447e.py
- keep/api/models/db/migrations/versions/2024-09-08-17-51_1aacee84447e.py
- keep/api/models/db/rule.py
- keep/api/routes/rules.py
- tests/test_rules_api.py
- tests/test_rules_engine.py
> feat: improve correlation rules form

- keep/api/api.py
close https://github.com/keephq/keep/issues/1876
> fix: stop the workflow manager thread

- keep/api/arq_worker.py
- keep/api/tasks/healthcheck_task.py
close https://github.com/keephq/keep/issues/1882
> fix: redis worker

- keep/api/core/db.py
> fix: Update db.py missing unique_api_key_id

- tests/test_workflow_execution.py
Closes #1785 
Another theory - the scheduler sometimes does not process workflows in workflows_to_run list
> fix: catching unstable test workflow execution 2

- keep-ui/app/rules/CorrelationTable.tsx
- keep-ui/utils/hooks/useRules.ts
- keep/api/core/db.py
- keep/api/routes/rules.py
Closes #1664
Show grouping rules and number of incidents created by the rule at rules table view
> feat: Make rules table more informative

- keep/api/routes/workflows.py
close https://github.com/keephq/keep/issues/1898
> fix: workflow is_disabled issue

- keep/api/routes/workflows.py
close https://github.com/keephq/keep/issues/1898
> fix: workflow is_disabled

- pyproject.toml
close https://github.com/keephq/keep/issues/1908
> chore(release): 0.24.2

- keep/api/routes/workflows.py
close https://github.com/keephq/keep/issues/1918
> fix: default workflows directory

- pyproject.toml
close https://github.com/keephq/keep/issues/1920
> chore(release): 0.24.4

- keep/api/core/db_on_start.py
close https://github.com/keephq/keep/issues/1922
> fix: don't fail the server if api key already in the secret manager

- keep-ui/app/workflows/builder/ReactFlowBuilder.tsx
- keep-ui/app/workflows/builder/ReactFlowEditor.tsx
- keep-ui/app/workflows/builder/builder.tsx
- keep-ui/app/workflows/builder/editors.tsx
- keep-ui/app/workflows/workflow-run-with-alert-modal.tsx
- keep-ui/utils/hooks/useWorkflowRun.ts
close https://github.com/keephq/keep/issues/1926
close https://github.com/keephq/keep/issues/1927
> feat: add the option to run workflow manually but with alert payload

- pyproject.toml
close https://github.com/keephq/keep/issues/1927
> chore(release): 0.24.5

- keep-ui/.eslintrc.json
- keep-ui/.prettierrc
- keep-ui/package-lock.json
- keep-ui/package.json
Closes #1947
Add local prettier config so code style would be consistent across contributions. Scope of this PR: Only local config for now. Later let's add it to the CI/CD actions.
> chore: add prettier configuration

- keep-ui/app/workflows/workflow-tile.tsx
- pyproject.toml
close https://github.com/keephq/keep/issues/1966
> fix: over flowing badge

- keep/providers/providers_service.py
close https://github.com/keephq/keep/issues/1962
> fix: clean secret if service already exists

- keep-ui/app/workflows/builder/builder-store.tsx
- keep-ui/app/workflows/builder/editors.tsx
Closes #1971
fixed the disabled input issue and auto-deploy issue
> fix(ui): the disabled input issue and auto deploy issue

- docs/deployment/kubernetes.mdx
close https://github.com/keephq/keep/issues/2054
> fix(docs): k8s outdated

- keep-ui/app/incidents/[id]/incident-workflow-sidebar.tsx
- keep-ui/app/incidents/[id]/incident-workflow-table.tsx
> fix: do not render IncidentWorkflowSidebar if no selectedExecution

- scripts/simulate_alerts.py
Close https://github.com/keephq/keep/issues/2069
> chore(scripts): update simulate_alerts.py with sleep interval as configurable

- keep-ui/app/incidents/[id]/incident-info.tsx
- keep-ui/app/incidents/incident.tsx
- keep-ui/app/incidents/incidents-table.tsx
- keep-ui/app/incidents/statuses.tsx
> feat: show status and severity at incident detail view page

- docs/providers/overview.mdx
Fixed smtp card in docs
Closes #2110
> fix: docs smtp card

- keep/api/core/db.py
- keep/rulesengine/rulesengine.py
> fix: Optimize flushing in  add_alerts_to_incident

- keep/api/routes/incidents.py
Closes #2125
During local development, creating an incident succeeds, but first an error toast is displayed.
> fix(api): serialize the UUID before passing off to pusher

- scripts/simulate_alerts.sh
Closes #2126
Fixes paths of the scripts/simulate_alerts.py directory.
> fix(scripts): simulate_alerts.sh to point to the right virtualenv path and also support running from any directory

- keep/providers/splunk_provider/splunk_provider.py
> chore: add additional debug logs to Splunk provider

- pyproject.toml
close https://github.com/keephq/keep/issues/2144
> chore(release): 0.25.3

- keep/providers/splunk_provider/splunk_provider.py
> refactor: more robust scopes validation

- keep-ui/app/alerts/alert-name.tsx
> fix: clamp alert name to up to 3 lines

- keep/identitymanager/authverifierbase.py
- pyproject.toml
close https://github.com/keephq/keep/issues/2160
> feat(api): don't update the key every time but every interval

- keep/api/core/db.py
Closes #2188
fix fail of with_incidents with `with_incidents=False`
> fix: alerts_with_start can have 2 columns if with_incidents is False

- examples/workflows/consts_and_vars.yml
- examples/workflows/sud.yml
- keep-ui/app/workflows/builder/ReactFlowEditor.tsx
- keep-ui/app/workflows/builder/builder.tsx
- keep-ui/app/workflows/builder/editors.tsx
- keep-ui/app/workflows/builder/utils.tsx
- keep-ui/app/workflows/workflow-menu.tsx
- keep-ui/utils/hooks/useWorkflowRun.ts
- keep/contextmanager/contextmanager.py
- keep/iohandler/iohandler.py
- keep/parser/parser.py
- keep/step/step.py
- keep/workflowmanager/workflow.py
close https://github.com/keephq/keep/issues/2194
> feat(workflows): consts and vars support

- keep-ui/app/incidents/[id]/incident-info.tsx
- keep-ui/app/incidents/create-or-update-incident.tsx
- keep-ui/app/incidents/incidents-table.tsx
- keep-ui/package-lock.json
- keep-ui/package.json
- keep-ui/utils/hooks/useIncidents.ts
> feat: WYSIWYG and formatting support for incidents summary

- .github/workflows/developer_onboarding_notification.yml
Closes #2170 
This PR introduces a new GitHub Action that automatically posts a comment on a pull request once it has been merged into the main branch.
> feat: developer onboarding notification added

- keep-ui/package-lock.json
- keep-ui/package.json
> chore(deps): posthog latest (1.167.1)

- keep/api/core/db.py
- keep/api/models/db/migrations/versions/2024-10-14-08-34_83c1020be97d.py
- tests/test_incidents.py
> fix: When assigning alert to in cident by alert id, get all alerts with same fingerprints + fix for SQLite migrations

- keep-ui/app/alerts/ColumnSelection.tsx
- keep-ui/app/alerts/alert-table-tab-panel.tsx
- keep-ui/app/alerts/alert-table-utils.tsx
- pyproject.toml
close https://github.com/keephq/keep/issues/2216
> feat: searchable columns + nested

- keep-ui/app/alerts/alerts.tsx
- keep-ui/app/incidents/[id]/incident-info.tsx
- keep-ui/app/incidents/incidents-table.tsx
- keep-ui/app/workflows/manual-run-workflow-modal.tsx
- keep/api/routes/workflows.py
- keep/workflowmanager/workflowscheduler.py
Closes #2197 
https://github.com/user-attachments/assets/70b49746-fa88-4b73-bced-462d7c64a28a
> feat: Possibility to run workflows for incidents manually

- keep/api/tasks/process_event_task.py
- keep/providers/base/base_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/2233
> fix(deduplication): allow nested fields in dedup

- keep/api/tasks/process_event_task.py
- keep/iohandler/iohandler.py
- keep/providers/openobserve_provider/openobserve_provider.py
- tests/test_iohandler.py
close https://github.com/keephq/keep/issues/2241
> feat(openobserve): improvements and fixes

- examples/workflows/new_github_stars.yml
- keep/providers/github_provider/github_provider.py
> fix(provider): github stars index +1

- docs/deployment/kubernetes/overview.mdx
- docs/deployment/secret-manager.mdx
close https://github.com/keephq/keep/issues/2301
> docs(k8s): read environment variable from secret

- docs/deployment/kubernetes/installation.mdx
close https://github.com/keephq/keep/issues/2303
> docs: better docs on ingress

- keep-ui/app/frigade-provider.tsx
- keep-ui/app/layout.tsx
- keep-ui/app/settings/webhook-settings.tsx
- keep-ui/components/navbar/Navbar.tsx
- keep-ui/components/navbar/Onboarding.tsx
- keep-ui/components/navbar/UserInfo.tsx
- keep-ui/package-lock.json
- keep-ui/package.json
- keep/api/models/alert.py
> feat(ui): onboarding experience using Frigade

- keep/api/core/db.py
> fix: limit and offset in incident alerts

- keep/api/api.py
- pyproject.toml
close https://github.com/keephq/keep/issues/2389
> feat(api): add version on startup logs

- keep/providers/pagerduty_provider/pagerduty_provider.py
> fix: typo pagerduty

- keep/providers/pagerduty_provider/pagerduty_provider.py
> fix(pd): another typo in PagerDuty

- keep/api/core/db.py
> fix: Resolved incidents can't be a target for RuleEngine

- pyproject.toml
None
Closes https://github.com/keephq/keep/issues/2527
> chore(release): new version 0.29.1

- pyproject.toml
None
Closes https://github.com/keephq/keep/issues/2574
> chore(release): new version 0.29.3

- pyproject.toml
close https://github.com/keephq/keep/issues/2624
> chore(version): bump version

- keep-ui/app/api/copilotkit/route.ts
> fix: move copilotkit initialization to the POST function

- keep-ui/app/(keep)/alerts/alert-presets.tsx
- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/app/(keep)/alerts/alert-table.tsx
- keep-ui/shared/lib/server/getConfig.ts
- keep-ui/utils/hooks/useSearchAlerts.ts
close https://github.com/keephq/keep/issues/2600
> feat(ui): better presets modal

- keep/providers/providers_factory.py
> fix: override `authentication` in `provider_auth`

- examples/workflows/businesshours.yml
- keep-ui/shared/ui/utils/showErrorToast.tsx
- keep/api/tasks/notification_cache.py
- keep/api/tasks/process_event_task.py
- keep/functions/__init__.py
- keep/iohandler/iohandler.py
- keep/providers/prometheus_provider/alerts_mock.py
- poetry.lock
- pyproject.toml
- tests/test_functions.py
close https://github.com/keephq/keep/issues/2663
> feat(api): add business hours 

- keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
- keep-ui/shared/api/ApiClient.ts
> fix: api client fix for read-only and empty responses

- keep/api/core/demo_mode.py
- keep/parser/parser.py
- keep/providers/providers_factory.py
- keep/workflowmanager/workflowscheduler.py
> fix: polish scripts and workflows for readonly

- keep/api/core/demo_mode.py
- scripts/simulate_alerts.py
None
Closes https://github.com/keephq/keep/issues/2680
> feat: AI Demo

- .github/workflows/test-pr.yml
- keep/api/core/dependencies.py
- keep/api/routes/topology.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
> feat: parallel tests execution with xdist

- keep/providers/victoriametrics_provider/victoriametrics_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/2689
> fix: add severity to vm

- keep/providers/azuremonitoring_provider/azuremonitoring_provider.py
to cover case when data.essentials.alertRule is None
Closes #2708
> fix: alert formatting for AzureMonitoring provider

- docs/providers/documentation/grafana_oncall-provider.mdx
- keep/providers/grafana_oncall_provider/grafana_oncall_provider.py
OnCall provider was actually a duplicate of the Grafana Incident provider. Fixed.
Closes https://github.com/keephq/keep/issues/2716
> fix: OnCall provider and docs

- keep-ui/features/same-incidents-in-the-past/ui/change-same-incident-in-the-past-form.tsx
None
Closes https://github.com/keephq/keep/issues/2731
> fix: incident linking

- keep/api/core/db.py
> fix: Handle Duplication entry error in set_last_alert

- keep/api/core/db.py
> fix: Use SELECT FOR UPDATE to prevent race conditions in set_last_alert

- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep/providers/teams_provider/teams_provider.py
- keep/providers/victoriametrics_provider/victoriametrics_provider.py
before:
https://github.com/user-attachments/assets/826a6dab-c2cc-4418-9023-cd8f1e6774d9
after:
https://github.com/user-attachments/assets/ffe4b3bc-459f-4c20-938d-d5df5f7ce76b
> fix: small UI issue and victoriametrics best efforts

- keep/api/core/db.py
None
Closes https://github.com/keephq/keep/issues/2750
> fix: sessions in /ai/stats

- keep-ui/app/(keep)/extraction/create-or-update-extraction-rule.tsx
- keep-ui/app/(keep)/mapping/create-or-edit-mapping.tsx
- keep-ui/app/(keep)/mapping/layout.tsx
- keep-ui/app/(keep)/mapping/mapping.tsx
> feat: mapping page sidebar

- keep/api/core/demo_mode.py
> fix: Use alert fingerprints instead of ids to assign alerts to incidents

- keep/api/routes/workflows.py
- pyproject.toml
close https://github.com/keephq/keep/issues/2779
> fix(api): yaml breaklines

- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
- keep-ui/app/(keep)/providers/provider-tile.tsx
- keep-ui/package-lock.json
- keep-ui/package.json
- keep-ui/utils/helpers.ts
- keep-ui/utils/hooks/useWorkflowInitialization.ts
> refactor: remove heavy frontend deps

- keep/api/routes/workflows.py
- keep/workflowmanager/workflowstore.py
- pyproject.toml
close https://github.com/keephq/keep/issues/2791
> feat(api): unique id

- keep/api/core/db.py
> fix: Catch lastalert deadlocks

- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
> fix: do not convert data to iso string if it's alredy an ISO string

- keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
- pyproject.toml
close https://github.com/keephq/keep/issues/2802
> fix(ui): cel validation

- keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-menu.tsx
> fix: body format on DELETE incidents/{id}/alerts

- keep/providers/datadog_provider/datadog_provider.py
close https://github.com/keephq/keep/issues/2808
> fix(api): datadog

- docs/deployment/monitoring.mdx
- docs/mint.json
- keep-ui/app/api/healthcheck/route.ts
None
Closes https://github.com/keephq/keep/issues/2821
> feat: healthcheck

- keep/providers/base/base_provider.py
- pyproject.toml
Wrong format of `lastReceived` when none provided
> fix(kafka): lastReceived in ISO format

- keep-ui/app/(keep)/workflows/builder/builder-workflow-testrun-modal.tsx
- keep-ui/app/(keep)/workflows/builder/builder.tsx
- keep-ui/app/(keep)/workflows/builder/types.ts
- keep-ui/app/(keep)/workflows/builder/workflow-execution-results.tsx
- keep-ui/app/(keep)/workflows/workflow-definition-yaml.tsx
- keep-ui/shared/api/ApiClient.ts
- keep-ui/utils/hooks/useWorkflowExecutions.ts
- keep/api/core/db.py
- keep/api/models/workflow.py
- keep/api/routes/workflows.py
- keep/providers/mysql_provider/mysql_provider.py
- keep/providers/openai_provider/openai_provider.py
- keep/providers/slack_provider/slack_provider.py
- keep/workflowmanager/workflowscheduler.py
close https://github.com/keephq/keep/issues/2840
> feat(ui): better wf execution page

- keep/api/routes/preset.py
> fix: import UUID

- keep/api/core/db.py
None
Closes https://github.com/keephq/keep/issues/2848
> fix: linked providers performance

- keep-ui/app/(keep)/alerts/alert-push-alert-to-server-modal.tsx
close https://github.com/keephq/keep/issues/2850
> fix(ui): add alert from UI

- keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
add timeout to queries
close https://github.com/keephq/keep/issues/2853
> fix(api): gcp timeout

- keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
close https://github.com/keephq/keep/issues/2853
> fix(api): timeout

- keep/api/core/demo_mode.py
> fix: demo mode api key

- keep/api/bl/incidents_bl.py
- keep/api/core/db.py
- keep/api/utils/enrichment_helpers.py
- poetry.lock
- pyproject.toml
- tests/test_incidents.py
> fix: Tests and fixes for IncidentBl

- examples/workflows/ifelse.yml
- keep/api/core/db.py
- keep/contextmanager/contextmanager.py
- keep/step/step.py
- keep/workflowmanager/workflow.py
- pyproject.toml
- tests/test_workflow_execution.py
close https://github.com/keephq/keep/issues/2882
> feat(api): add continue to workflows

- examples/workflows/bigquery.yml
- keep/providers/bigquery_provider/bigquery_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/2884
> fix(api): bigquery

- keep-ui/app/(keep)/providers/provider-form.tsx
Closes #2915 https://github.com/keephq/keep/issues/2915
Round the provider form localhost warning corners
Before:
After:
> fix: Round the provider form localhost warning corners

- keep-ui/auth.config.ts
- pyproject.toml
close https://github.com/keephq/keep/issues/2920
> fix(ui): keycloak

- keep-ui/app/(keep)/topology/ui/map/getNodesAndEdgesFromTopologyData.ts
close https://github.com/keephq/keep/issues/2925
> fix(ui): service

- keep/api/routes/metrics.py
- pyproject.toml
> feat(api): no auth for processing metrics

- keep-ui/utils/hooks/useIncidents.ts
- keep/workflowmanager/workflowscheduler.py
> fix: Filter out deleted and resolved incidents from association form

- keep-ui/tsconfig.json
close https://github.com/keephq/keep/issues/2946
> fix(ui): sources

- keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
close https://github.com/keephq/keep/issues/2964
> fix: CEL with quote

- keep/providers/smtp_provider/smtp_provider.py
> fix(smtp): no encryption

- keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
- keep-ui/app/(keep)/alerts/alerts-rules-builder.tsx
close https://github.com/keephq/keep/issues/2674
> feat(ui): minor changes in the uI

- keep/providers/grafana_provider/grafana_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/2978
> feat(api): grafana extra values

- keep/providers/clickhouse_provider/clickhouse_provider.py
None
Closes https://github.com/keephq/keep/issues/2982
> fix: allow clickhouse protocol variaty

- docs/overview/howdoeskeepgetmyalerts.mdx
Close #2975
missed to update doc for issue #2975
> docs: Update howdoeskeepgetmyalerts.mdx

- keep/api/routes/incidents.py
> fix: WorkflowExecutionsPaginatedResultsDto expects WorkflowExecutionDTO instances

- docs/workflows/syntax/triggers.mdx
> fix: interval docs

- keep/api/models/alert.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3023
> fix: incident reoslve on default value

- README.md
> fix(readme): minor change

- keep/api/logging.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3051
> feat(api): uvicorn

- keep/providers/grafana_provider/grafana_provider.py
- pyproject.toml
> fix(grafana): print number of alerts in payload

- keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
- keep-ui/app/(keep)/workflows/builder/editors.tsx
- keep-ui/app/(keep)/workflows/workflow-tile.tsx
- keep-ui/components/ui/DynamicProviderIcon.tsx
- keep-ui/components/ui/index.ts
close https://github.com/keephq/keep/issues/3063
> fix(ui): svg dynamic provider is not working

- keep/api/core/dependencies.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3086
> fix(pusher): self signed certificate

- keep/api/routes/alerts.py
- keep/providers/base/base_provider.py
> fix: provider id

- examples/workflows/consts_and_dict.yml
- keep/functions/__init__.py
- tests/test_functions.py
close https://github.com/keephq/keep/issues/3088
> feat(api): add keep.dictget

- examples/workflows/create_alert_in_keep.yml
- keep/providers/keep_provider/keep_provider.py
None
Closes https://github.com/keephq/keep/issues/3097
> feat: workflow to create alerts

- examples/workflows/create_alert_from_vm_metric.yml
- keep/providers/keep_provider/keep_provider.py
close https://github.com/keephq/keep/issues/3115
> feat(api): customize fingerprint

- examples/workflows/update_workflows_from_http.yml
- keep/providers/keep_provider/keep_provider.py
None
Closes https://github.com/keephq/keep/issues/3149
> docs: example wf, pull wf from HTTP

- keep/providers/checkmk_provider/checkmk_provider.py
close https://github.com/keephq/keep/issues/3166
> fix(api): checkmk service

- keep/providers/clickhouse_provider/clickhouse_provider.py
- pyproject.toml
close #3170 
better validation in Clickhouse provider:
> feat(clickhouse): optional SSL verification

- keep/api/observability.py
- keep/parser/parser.py
- keep/workflowmanager/workflowmanager.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3179
> feat(api): workflows cache

- keep/api/routes/incidents.py
- tests/test_alert_evaluation.py
- tests/test_iohandler.py
> fix: iohandler tests

- keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
close https://github.com/keephq/keep/issues/3197
> feat(ui): allow nested labels on grouped by

- keep/api/routes/preset.py
close #3208 
close keep incident: 3b90d981-696d-4912-b51f-53850a13bdff/alerts
> fix(api): preset tabs

- keep/providers/gke_provider/gke_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3213
> feat(api): gke improvements

- keep/api/logging.py
- keep/api/observability.py
- keep/providers/checkmk_provider/checkmk_provider.py
> fix: renaming for cloud run

- keep/providers/kibana_provider/kibana_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3241
> feat(api): kibana 8.16.0

- keep/providers/kibana_provider/kibana_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3244
> feat(api): kibana SIEM

- keep/api/logging.py
close https://github.com/keephq/keep/issues/3266
> fix(api): logs

- keep-ui/features/filter/facets-panel.tsx
- keep-ui/features/incident-list/ui/incident-list.tsx
- keep-ui/features/incident-list/ui/incident-table-component.tsx
- keep-ui/features/incident-list/ui/incidents-table.tsx
Closes #3265 
- make incident list table respect parent width
- replace severity badge with border indicator (like in alerts) to fit more data into smaller screen
> fix: incident list horizontal scroll

- poetry.lock
None
Closes https://github.com/keephq/keep/issues/3305
> chore(version): bump

- poetry.lock
Reverts keephq/keep#3304
Closes https://github.com/keephq/keep/issues/3307
> fix: Revert "chore(version): bump"

- keep/rulesengine/rulesengine.py
- pyproject.toml
- tests/test_rules_engine.py
close https://github.com/keephq/keep/issues/3311
> fix(api): rules engine

- examples/workflows/clickhouse_multiquery.yml
- keep/providers/servicenow_provider/servicenow_provider.py
- tests/test_incidents.py
close https://github.com/keephq/keep/issues/3314
> fix(api): example

- keep/rulesengine/rulesengine.py
- pyproject.toml
- tests/test_rules_engine.py
close https://github.com/keephq/keep/issues/3311
> fix(api): at_sign

- keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
Revised the "value" properties for SelectItem components to improve clarity and consistency. This change ensures the keys explicitly indicate the resolution status for better code readability and maintenance.
Closes #3318
> fix: Update SelectItem values to use more descriptive keys

- keep/api/models/db/migrations/versions/2025-02-05-15-46_e343054ae740.py
> chore: 3318 bug rules created via UI has wrong resolve on values

- keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
- keep-ui/app/(keep)/workflows/workflows.client.tsx
- keep-ui/entities/workflows/model/useWorkflowActions.ts
- keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
- keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
- keep-ui/utils/hooks/useWorkflowDetail.ts
- keep-ui/utils/hooks/useWorkflowsV2.ts
- pyproject.toml
close https://github.com/keephq/keep/issues/3335
> fix(ui): saving workflow doesn't refresh cache

- README.md
> fix: readme broken

- keep/api/core/alerts.py
> fix(api): Fix bug when order by was broken on alerts query endpoint

- pyproject.toml
close https://github.com/keephq/keep/issues/3360
> feat: release 0.36

- keep/api/core/alerts.py
- keep/api/core/cel_to_sql/sql_providers/base.py
- keep/api/core/cel_to_sql/sql_providers/get_cel_to_sql_provider_for_dialect.py
- keep/api/core/cel_to_sql/sql_providers/mysql.py
- keep/api/core/cel_to_sql/sql_providers/postgresql.py
- keep/api/core/cel_to_sql/sql_providers/sqlite.py
- keep/api/core/facets.py
- keep/api/core/incidents.py
- tests/cel_to_sql/cel-to-sql-test-cases.json
- tests/cel_to_sql/test_cel_to_sql.py
Closes #3366
- Add proper handling for single-quotes and double-quotes in CEL-to-SQL translation
- Add testcases for single-quotes and double-quotes
- Add tescases for startsWith and endsWith operators
> fix: Improve handling of quotes/double-quotes during CEL to SQL translation

- keep/api/core/db.py
- keep/api/models/db/alert.py
close https://github.com/keephq/keep/issues/3373
> fix(api): linked provider slowliness

- keep/providers/site24x7_provider/site24x7_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3377
> fix(api): site24x7

- keep-ui/features/filter/facets-panel.tsx
- keep-ui/features/incident-list/ui/incident-list.tsx
- keep/api/core/cel_to_sql/properties_metadata.py
- keep/api/core/facets.py
> fix: Adding not existing in Incident table facet causes app to crash

- .github/workflows/test-docs.yml
- .github/workflows/test-pr-e2e.yml
- .github/workflows/test-pr.yml
- keep/api/models/workflow.py
> chore: update github actions cache to latest version

- keep/api/core/db.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3411
> fix(api): last alert hash

- keep-ui/shared/api/ApiClient.ts
> fix: facet options in Keep readonly mode

- examples/workflows/incident-enrich.yaml
- keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
- keep-ui/app/(keep)/alerts/alert-run-workflow-modal.tsx
- keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-action-tray.tsx
- keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
- keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.css
- keep-ui/app/(keep)/incidents/[id]/incident-header.tsx
- keep-ui/app/(keep)/incidents/[id]/incident-layout-client.tsx
- keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
- keep-ui/app/(keep)/workflows/manual-run-workflow-modal.tsx
- keep-ui/components/ui/ResizableColumns.tsx
- keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
- keep/api/bl/incidents_bl.py
- keep/api/core/db.py
- keep/api/models/db/enrichment_event.py
- keep/api/routes/workflows.py
- keep/functions/__init__.py
- keep/providers/base/base_provider.py
- keep/workflowmanager/workflowscheduler.py
- pyproject.toml
- tailwind.config.js
- tests/test_functions.py
close #3420 with a few more improvements
https://github.com/user-attachments/assets/4acf9ca5-309f-4ba9-9b91-426258227000
> feat: enrich incident

- keep/api/tasks/process_event_task.py
close https://github.com/keephq/keep/issues/3429
> fix: logs wip

- keep/providers/keep_provider/keep_provider.py
- pyproject.toml
> fix: clean workflow

- keep-ui/auth.config.ts
- keep-ui/shared/api/ApiClient.ts
- keep-ui/shared/api/server/createServerApiClient.ts
- pyproject.toml
close https://github.com/keephq/keep/issues/3458
> fix: add headers on server side requests

- keep/providers/dynatrace_provider/dynatrace_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3464
> fix: dynatrace webhook

- keep/api/models/alert.py
- tests/test_alert_dto.py
close https://github.com/keephq/keep/issues/3467
> fix: unix timestamp

- keep-ui/next.config.js
- keep-ui/shared/api/server/createServerApiClient.ts
- oauth2proxy/docker-compose-oauth2proxy.yml
- oauth2proxy/nginx.conf
- pyproject.toml
close https://github.com/keephq/keep/issues/3458
> fix: 401 error east-west from frontend to backend 

- keep/rulesengine/rulesengine.py
- tests/test_rules_engine.py
This update ensures that new incidents are only created for alerts with a "firing" status, preventing unnecessary incidents for resolved or non-firing alerts. A corresponding test was added to validate this behavior in the rules engine.
Closes #3418
> fix: Restrict incident creation to firing alerts only

- docs/deployment/authentication/oauth2proxy-auth.mdx
close https://github.com/keephq/keep/issues/3470
> docs: oauth2 proxy

- docs/providers/documentation/checkly-provider.mdx
> fix: checkly docs

- keep/api/core/db.py
- keep/rulesengine/rulesengine.py
- tests/test_rules_engine.py
Implemented logic to track and link new incidents to previously resolved or deleted incidents for the same rule. Updated database schema, core logic, and test cases to ensure correct assignment of `same_incident_in_the_past_id`. This enhances incident continuity and history tracking.
Closes #3315
> feat: Add support for linking new incidents to past resolved incidents

- keep/identitymanager/authverifierbase.py
close https://github.com/keephq/keep/issues/3481
> feat: add logs

- keep/rulesengine/rulesengine.py
Modified `_get_or_create_incident` to return both the incident and a flag indicating if it was newly created. Updated corresponding logic to handle the new return type, streamlining incident creation and status tracking.
Closes #3491
> fix: Refactor `_get_or_create_incident` to return tuple of incident and creation flag

- keep-ui/app/(keep)/extraction/[rule_id]/executions/[execution_id]/page.tsx
- keep-ui/app/(keep)/extraction/[rule_id]/executions/page.tsx
- keep-ui/app/(keep)/extraction/extractions-table.tsx
- keep-ui/app/(keep)/extraction/run-extraction-modal.tsx
- keep-ui/utils/hooks/useEnrichmentEvents.ts
- keep/api/bl/enrichments_bl.py
- keep/api/core/db.py
- keep/api/models/db/alert.py
- keep/api/routes/extraction.py
> feat: extraction executions

- examples/workflows/mustache-paths-example.yml
- keep-ui/features/workflow-execution-results/ui/WorkflowExecutionLogs.tsx
- keep/api/bl/enrichments_bl.py
- keep/providers/python_provider/python_provider.py
> fix: logs enrichment

- keep/api/models/alert.py
- tests/test_alert_dto.py
close https://github.com/keephq/keep/issues/3507
> fix: revert tz

- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
> fix: alert description line clamp in incident/alerts

- keep/providers/checkmk_provider/checkmk_provider.py
fixing parsing
close https://github.com/keephq/keep/issues/3533
> fix: checkmk

- pyproject.toml
close https://github.com/keephq/keep/issues/3541
> feat(api): release 0.37.0

- examples/workflows/execute-workflow-example.yml
- keep/api/routes/workflows.py
> feat: execute workflow from slack

- keep/providers/grafana_provider/grafana_provider.py
close https://github.com/keephq/keep/issues/3544
> feat: small grafana improvement

- keep/api/models/db/migrations/versions/2025-02-19-15-32_35ebba262eb0.py
close https://github.com/keephq/keep/issues/3574
> fix: double-headed-migration

- keep/providers/datadog_provider/datadog_provider.py
close https://github.com/keephq/keep/issues/3572
> feat: datadog snapshot

- scripts/simulate_alerts.py
close https://github.com/keephq/keep/issues/3586
> fix: remove old incidents

- keep-ui/entrypoint.sh
- pyproject.toml
close https://github.com/keephq/keep/issues/3587
> fix: entrypoint

- keep-ui/entrypoint.sh
- pyproject.toml
close https://github.com/keephq/keep/issues/3587
> fix(ui): entry

- keep-ui/features/workflows/builder/ui/BuilderChat/builder-chat.tsx
- keep-ui/features/workflows/builder/ui/Editor/StepEditor.tsx
- keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
- keep-ui/widgets/workflow-builder/builder.tsx
> fix: wf step test

- keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
- keep-ui/app/(keep)/alerts/alerts-table-body.tsx
- keep-ui/features/filter/facet.tsx
- keep-ui/features/filter/facets-panel.tsx
- keep-ui/features/filter/models.tsx
> feat: Make filter empty state reachable when nothing is selected in Facet

- keep-ui/components/ui/DynamicProviderIcon.tsx
- keep-ui/entities/workflows/lib/getHumanReadableInterval.ts
- keep-ui/entities/workflows/lib/getLayoutedWorkflowElements.ts
- keep-ui/entities/workflows/lib/getTriggerDescription.ts
- keep-ui/entities/workflows/model/types.ts
- keep-ui/entities/workflows/model/workflow-store.ts
- keep-ui/entities/workflows/ui/NodeTriggerIcon.tsx
- keep-ui/entities/workflows/ui/WorkflowTriggerBadge.tsx
- keep-ui/features/workflows/builder/ui/BuilderChat/AddStepUI.tsx
- keep-ui/features/workflows/builder/ui/BuilderChat/AddTriggerUI.tsx
- keep-ui/features/workflows/builder/ui/BuilderChat/StepPreview.tsx
- keep-ui/features/workflows/builder/ui/BuilderChat/builder-chat.tsx
- keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
- keep-ui/features/workflows/builder/ui/Editor/TriggerEditor.tsx
- keep-ui/features/workflows/builder/ui/WorkflowNode.tsx
> fix: better triggers in workflow ai

- pyproject.toml
close https://github.com/keephq/keep/issues/3613
> fix: version

- docs/overview/alertseverityandstatus.mdx
> fix: typo in alertseverityandstatus.mdx

- docs/incidents/facets.mdx
- keep-ui/features/incident-list/ui/incident-list.tsx
- keep/api/core/incidents.py
Closes #3625
- Add "Linked incident" facet
- Fix broken sorting on Incidents page
> feat: Facet for linked or unlinked past incidents

- keep/providers/amazonsqs_provider/amazonsqs_provider.py
- keep/providers/cloudwatch_provider/cloudwatch_provider.py
- keep/providers/eks_provider/eks_provider.py
- keep/providers/incidentmanager_provider/incidentmanager_provider.py
- keep/providers/s3_provider/s3_provider.py
close https://github.com/keephq/keep/issues/3634
> fix: boto3 auth

- keep-ui/entities/workflows/lib/getLayoutedWorkflowElements.ts
- keep-ui/entities/workflows/lib/parser.ts
- keep-ui/entities/workflows/model/__tests__/types.test.ts
- keep-ui/entities/workflows/model/__tests__/workflow-store.test.tsx
- keep-ui/entities/workflows/model/types.ts
- keep-ui/entities/workflows/model/useWorkflowActions.ts
- keep-ui/entities/workflows/model/workflow-store.ts
- keep-ui/entities/workflows/model/yaml.types.ts
- keep-ui/entities/workflows/ui/NodeTriggerIcon.tsx
- keep-ui/features/workflows/ai-assistant/lib/utils.ts
- keep-ui/features/workflows/builder/lib/utils.tsx
- keep-ui/features/workflows/builder/ui/Editor/ReactFlowEditor.tsx
- keep-ui/features/workflows/builder/ui/Editor/StepEditor.tsx
- keep-ui/features/workflows/builder/ui/Editor/TriggerEditor.tsx
- keep-ui/features/workflows/builder/ui/WorkflowEdge.tsx
- keep-ui/features/workflows/builder/ui/WorkflowNode.tsx
- keep-ui/features/workflows/builder/ui/WorkflowToolbox.tsx
- keep-ui/features/workflows/test-run/ui/workflow-test-run-modal.tsx
- keep-ui/utils/reactFlow.ts
- keep-ui/widgets/workflow-builder/workflow-builder.tsx
> fix: don't allow adding condition in condition or loop in the loop

- keep-ui/app/(keep)/alerts/alert-grouped-row.tsx
> fix(ui): viewed eye alignment

- ee/identitymanager/identity_managers/azuread/azuread_authverifier.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3658
> feat(api): support azuread token v2

- ee/identitymanager/identity_managers/azuread/azuread_authverifier.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3658
> feat(api): azurev2

- ee/identitymanager/identity_managers/azuread/azuread_authverifier.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3658
> fix: azure

- keep-ui/features/incident-list/ui/incident-list.tsx
- keep-ui/utils/hooks/useIncidents.ts
- keep-ui/utils/hooks/usePusher.ts
> feat: time select for incidents page

- keep/api/core/facets.py
- keep/api/core/incidents.py
Closes #3666
- Fix "source" facet
- Fix 500 error from /facet/options when facet points to not existing field
> fix: Use inner join for incident instead of outerjoin and fix "source" facet

- .github/workflows/but-to-project.yml
close https://github.com/keephq/keep/issues/3673
> feat: bug to board

- keep/api/routes/providers.py
close keep alert: 06060c5906146f9ea4d433b35536c196ea86f19d836a3de63e3ea9d923c5b2ed
close keep alert: 86bd73a66c6210c69472c3a1adb9ec53408f3d555d2f1cc9fd827c8d56242d45
close keep alert: 1959127bfa5f5504a76c59a04bb0a4bff565c9c51f77a26066939d55a32b9cd2
> fix: providerInfo could be None

- .github/workflows/auto-resolve-keep.yml
> fix: pull request to push

- keep-ui/features/incident-list/ui/incident-game.tsx
- keep-ui/features/incident-list/ui/incidents-table.tsx
In response to observed suboptimal engagement metrics within the incident management workflow environment, we hereby propose the integration of interactive ludic elements into the enterprise-level B2B monitoring solution. This implementation addresses the documented phenomenon of attentional fatigue and diminished cognitive engagement experienced by technical personnel during extended periods of incident surveillance.
The current interface architecture, while functionally adequate for data visualization purposes, fails to maintain optimal levels of user attention during periods of low incident activity. This attentional deficit potentially compromises response time metrics when critical incidents subsequently manifest.
Our proposed solution entails the seamless incorporation of a …
> feat: incident arcade

- keep/providers/datadog_provider/datadog_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3733
> feat: datadog events v2

- keep/providers/datadog_provider/datadog_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3733
> fix: list monitors

- keep/api/core/db.py
- keep/rulesengine/rulesengine.py
- tests/test_incidents.py
- tests/test_rules_engine.py
> fix: Fix support for incident approval in rules engine

- examples/workflows/run_github_action.yaml
- examples/workflows/update_workflows_from_s3.yml
- keep/providers/datadog_provider/datadog_provider.py
- keep/providers/github_provider/github_provider.py
- keep/providers/keep_provider/keep_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3738
> feat: Ability to run GH actions & fix for wf removal

- docs/deployment/secret-store.mdx
- keep/secretmanager/awssecretmanager.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3744
> feat: aws kms key id for secrets

- keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
- keep-ui/app/(keep)/rules/CorrelationTable.tsx
close https://github.com/keephq/keep/issues/3716
> fix: empty correlation

- keep/api/core/db.py
- keep/api/routes/rules.py
close https://github.com/keephq/keep/issues/3752
> fix: update incident name template

- keep/api/routes/workflows.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3763
> fix: can't run workflow on incident manually if trying to fetch alerts

- keep-ui/features/incident-list/ui/incident-list.tsx
- keep-ui/utils/hooks/useIncidents.ts
- pyproject.toml
Closes #3766
- Add filter for facet options to exclude not confirmed incidents
> fix: Facets filtering on Incidents displays values for not confirmed incidents

- keep-ui/app/(keep)/alerts/ColumnSelection.tsx
- keep-ui/app/(keep)/alerts/RowStyleSelection.tsx
- keep-ui/app/(keep)/alerts/SettingsSelection.tsx
- keep-ui/app/(keep)/alerts/ThemeSelection.tsx
- keep-ui/app/(keep)/alerts/TitleAndFilters.tsx
- keep-ui/app/(keep)/alerts/alert-grouped-row.tsx
- keep-ui/app/(keep)/alerts/alert-pagination-server-side.tsx
- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/app/(keep)/alerts/alert-table.tsx
- keep-ui/app/(keep)/alerts/alerts-table-body.tsx
- keep-ui/entities/alerts/ui/AlertName/AlertName.tsx
close https://github.com/keephq/keep/issues/3776
> feat: compact rows

- keep-ui/entities/incidents/model/useIncidentActions.tsx
- keep-ui/features/incident-list/ui/incidents-table.tsx
- keep/api/bl/incidents_bl.py
- keep/api/routes/incidents.py
Closes #3759
Added bulk deletion (incidents)
https://github.com/user-attachments/assets/425859c5-e60a-4c1f-8bf2-a84c765bc430
> feat: bulk delete (incidents)

- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
close https://github.com/keephq/keep/issues/3777
> fix: dense

- keep-ui/app/(keep)/alerts/alert-table-headers.tsx
- keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
- keep-ui/app/(keep)/alerts/alert-table-time-format.tsx
- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/app/(keep)/alerts/alert-table.tsx
close https://github.com/keephq/keep/issues/3779
> feat: adjustable time

- keep-ui/app/(keep)/alerts/ActionTraySelection.tsx
- keep-ui/app/(keep)/alerts/SettingsSelection.tsx
- keep-ui/app/(keep)/alerts/alerts-table-body.tsx
- keep-ui/entities/alerts/ui/AlertName/AlertName.tsx
https://github.com/user-attachments/assets/a5d7caf4-0414-4144-80a6-a08f7aec192b
> feat(ui): alert action tray

- keep/providers/deepseek_provider/deepseek_provider.py
Added a try-except block to ensure `max_tokens` is converted to an integer. Defaults to 1024 if input is invalid, preventing potential runtime errors.
Closes #3767
> fix: Validate and handle non-integer max_tokens input.

- keep-ui/app/(keep)/alerts/alert-table-headers.tsx
- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- tests/conftest.py
- tests/e2e_tests/test_filtering_sort_search_on_alerts.py
Closes #3786
- Make header change sort direction upon clicking (not just the arrow)
- Open E2E tests browser using big screen viewport to not be sensitive to small screens
> fix: Make header change sort direction upon clicking

- keep/api/core/alerts.py
Closes #3746
- Sort by lastalert.timestamp during facets calculation instead of alert.timestamp that caused slowness
> fix: Fix slowness in sqlite when hard limit is involved

- keep-ui/app/(keep)/providers/provider-semi-automated.tsx
- keep/api/routes/providers.py
> fix: add provider id to webhook template if provider is connected

- keep-ui/shared/api/ApiClient.ts
> fix(ui): add `/alerts/query` to allowed urls

- keep/providers/cloudwatch_provider/cloudwatch_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3817
> feat: log groups for CW

- keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
close https://github.com/keephq/keep/issues/3836
> feat: enrich from modal

- keep-ui/app/(keep)/alerts/alert-history.tsx
- keep-ui/app/(keep)/alerts/alert-menu.tsx
- keep-ui/app/(keep)/alerts/alerts.tsx
> fix: Cel query gets empty after opening alert modal in keep UI

- keep-ui/app/(keep)/workflows/manual-run-workflow-modal.tsx
- keep-ui/entities/workflows/ui/WorkflowTriggerBadge.tsx
Replaced ID-based selection with a more intuitive object-based approach using custom React-Select components. Added support for improved filtering, display of workflow details, and trigger badges in the dropdown. Simplifies interaction and enhances user experience.
Closes #3619
> fix: Workflow manual run modal improvements

- keep/providers/smtp_provider/smtp_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3853
> feat: list of addresses for SMTP

- keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
close https://github.com/keephq/keep/issues/3871
> fix: pagination

- keep/api/tasks/process_event_task.py
close keep incident: 2f82730d-4cb5-466d-81b1-1aecb316f375
close https://github.com/keephq/keep/issues/3874
> fix(api): strip

- keep-ui/app/(keep)/alerts/alert-table-headers.tsx
- keep-ui/app/(keep)/alerts/alert-table-list-format.tsx
- keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/app/(keep)/alerts/alert-table.tsx
close https://github.com/keephq/keep/issues/3876
> feat: list format

- examples/workflows/webhook_example.yml
- keep/providers/vectordev_provider/vectordev_provider.py
- keep/providers/webhook_provider/webhook_provider.py
- pyproject.toml
> fix: webhook provider

- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep/api/routes/alerts.py
- keep/api/utils/enrichment_helpers.py
Not sure how much will it impact performance (added `with_incident=true`) back.
https://github.com/user-attachments/assets/db9ba4ef-ee04-47c9-b400-454a4f952a30
> feat: incident link from alert table

- keep-ui/app/(keep)/rules/CorrelationPlaceholder.tsx
- keep-ui/app/(keep)/rules/CorrelationSidebar/RuleFields.tsx
close #3909 
Before (only default fields):
After:
> fix(ui): correlation rule fields

- keep/api/core/db.py
Replaced multiple direct accesses of `alert.fingerprint` with a single variable `fingerprint` to improve code readability and maintainability. Updated all related log messages and function calls accordingly. This reduces redundancy and potential errors in handling the fingerprint property.
Closes #3911
> fix: Refactor alert fingerprint logging for consistency.

- keep-ui/app/(keep)/rules/CorrelationSidebar/RuleFields.tsx
> fix: update available fields

- keep/providers/argocd_provider/argocd_provider.py
Closes #3922
Adds support for ArgoCD applications that have multiple sources. Applications with multiple sources currently causes the provider to error.
> fix: Fixes ArgoCD applications that have multiple sources

- keep/api/bl/incidents_bl.py
- keep/api/tasks/process_event_task.py
- keep/rulesengine/rulesengine.py
> feat: resolve manual incidents automatically

- docs/cli/installation.mdx
Tested on fresh mac:
close https://github.com/keephq/keep/issues/3950
close #3495
> fix: cli installation instructions

- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep/providers/netbox_provider/netbox_provider.py
> fix(ui): incident col and netbox provider

- keep-ui/features/incident-list/ui/incident-list.tsx
close https://github.com/keephq/keep/issues/3957
> fix: we forgot provider image on facets

- keep-ui/entities/workflows/lib/__tests__/parser.test.ts
- keep-ui/entities/workflows/lib/parser.ts
> fix: workflow ui removes conditions and foreach

- keep/api/bl/incidents_bl.py
- keep/api/tasks/process_event_task.py
- keep/rulesengine/rulesengine.py
Converted static method to instance method in `IncidentBl` to leverage class context. Introduced retry mechanism for `StaleDataError` to ensure robust incident resolution. Optimized logging to trigger only when incident names actually change.
Closes #3961 
close keep incident: df57af4c-8c55-4c96-8818-379a57ebbe68
> fix: Refactor incident resolution and improve database handling.

- keep/api/core/alerts.py
- keep/api/core/facets.py
Closes #3966
- Add error handling for alerts query and facet options query in case of SQL error (will return just empty array)
- Add support of fingerprint property to alerts CEL
close keep incident: bc827969-feb8-4d28-987c-fe66d4b900f7
> fix: Change join order in alerts query to prevent duplicated alerts

- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
> fix(ui): overflow none to incident field

- keep-ui/app/(keep)/workflows/manual-run-workflow-modal.tsx
- keep-ui/utils/hooks/useWorkflows.ts
> fix: manual workflow modal

- keep-ui/app/(keep)/alerts/alerts-table-body.tsx
- keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
> fix: handle duplicated row ids in alerts table rendering

- keep-ui/app/(keep)/alerts/alert-menu.tsx
- keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.tsx
- keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
- keep-ui/app/(keep)/topology/ui/map/getLayoutedElements.ts
- keep-ui/components/ui/RootCauseAnalysis.tsx
- keep/api/bl/enrichments_bl.py
- keep/providers/cilium_provider/cilium_provider.py
- keep/providers/github_provider/github_provider.py
- keep/providers/postgres_provider/postgres_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/3979
> feat: fixes and improvements for the demo

- keep/api/core/alerts.py
- keep/api/core/db.py
- keep/providers/slack_provider/slack_provider.py
- keep/workflowmanager/workflowmanager.py
- keep/workflowmanager/workflowscheduler.py
Updated workflows to handle incidents with enrichment data, refined fingerprint logic for incidents, and expanded filters to include incident-related mappings. Adjustments ensure better synchronization of alerts/incidents in workflows and improve Slack notifications with enriched metadata.
Closes #3958
> feat: Add incident handling and enrichment improvements

- keep/api/bl/enrichments_bl.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4001
> fix: enrichment.db_session 

- keep/api/routes/providers.py
close [#3011](https://github.com/keephq/keep/issues/3011)
> fix: comments for a few endpoints

- .github/workflows/test-pr-e2e.yml
- .github/workflows/test-pr-integrations.yml
- .github/workflows/test-pr-ut-ui.yml
- .github/workflows/test-pr-ut.yml
- keep/event_subscriber/event_subscriber.py
Closes #4014
- Set fail-fast to false so that failing E2E job does not cancel another E2E job in probress
> fix: Update concurrency group in workflow files for tests

- keep/api/models/db/migrations/versions/2025-03-13-14-08_c0e70149c9ec.py
close https://github.com/keephq/keep/issues/4023
> fix: migrations

- .github/workflows/test-pr-e2e.yml
> fix: e2e run for contributors

- keep/providers/victorialogs_provider/victorialogs_provider.py
- keep/providers/victoriametrics_provider/victoriametrics_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4030
> feat: allow insecure vm

- keep/providers/openobserve_provider/openobserve_provider.py
Updated the alert formatting logic to handle multiple group_by keys instead of a single key-value pair. Adjusted the AlertDto creation and fingerprint calculation to incorporate all group_by keys, ensuring better handling of aggregated alerts. This improves flexibility and correctness in alert processing.
Closes #4038
> fix: Support multiple group_by keys in alert formatting

- keep-ui/app/(keep)/alerts/ActionTraySelection.tsx
- keep-ui/app/(keep)/alerts/alert-table-headers.tsx
- keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/app/(keep)/alerts/alert-table.tsx
- tests/e2e_tests/test_filtering_sort_search_on_alerts.py
- tests/e2e_tests/test_pushing_prometheus_alerts.py
- tests/e2e_tests/utils.py
close https://github.com/keephq/keep/issues/4033
> feat: status as column like source

- keep-ui/app/globals.css
- tests/e2e_tests/test_end_to_end.py
- tests/e2e_tests/test_end_to_end_theme.py
- tests/e2e_tests/test_pushing_prometheus_alerts.py
- tests/e2e_tests/utils.py
close https://github.com/keephq/keep/issues/4028
> fix: theme selection

- keep-ui/app/(keep)/alerts/SettingsSelection.tsx
- keep-ui/app/(keep)/alerts/alert-menu.tsx
- keep-ui/app/(keep)/alerts/alert-preset-manager.tsx
- keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/app/(keep)/alerts/alert-table.tsx
- keep-ui/app/(keep)/alerts/alerts-table-body.tsx
- keep-ui/entities/alerts/ui/AlertName/AlertName.tsx
- keep-ui/utils/hooks/useExpandedRows.ts
- pyproject.toml
- tests/conftest.py
- tests/e2e_tests/test_end_to_end_theme.py
close https://github.com/keephq/keep/issues/4045
> feat(ui): expand

- keep-ui/app/(keep)/alerts/ViewAlertModal.tsx
- keep-ui/app/(keep)/mapping/create-or-edit-mapping.tsx
- keep-ui/app/(keep)/settings/webhook-settings.tsx
- keep-ui/features/workflow-execution-results/ui/WorkflowExecutionLogs.tsx
- keep-ui/features/workflows/ai-assistant/ui/StepPreview.tsx
- keep-ui/features/workflows/builder/ui/Editor/StepTest.tsx
- keep-ui/shared/ui/YAMLCodeblock/ui/MonacoYAMLEditor.tsx
- pyproject.toml
close https://github.com/keephq/keep/issues/4047
> fix: monaco onprem

- keep/api/routes/alerts.py
close https://github.com/keephq/keep/issues/4052
> fix: none is not allowed

- keep-ui/entities/incidents/model/useIncidentActions.tsx
- keep-ui/features/change-incident-severity/index.ts
- keep-ui/features/change-incident-severity/ui/incident-change-severity-select.tsx
- keep-ui/features/change-incident-severity/ui/incident-severity-select.tsx
- keep-ui/features/create-or-update-incident/ui/create-or-update-incident-form.tsx
- keep-ui/tailwind.config.js
- keep/api/core/db.py
- keep/api/models/incident.py
> feat: Add ability to assign incident severity during creation

- keep-ui/app/(keep)/maintenance/create-or-update-maintenance-rule.tsx
- keep-ui/app/(keep)/maintenance/model.ts
close [#3969](https://github.com/keephq/keep/issues/3969)
> fix: suppress

- keep-ui/app/(keep)/incidents/[id]/incident-header.tsx
- keep-ui/app/(keep)/incidents/[id]/incident-overview.tsx
close [#3699](https://github.com/keephq/keep/issues/3699)
> fix: minor oddities on the incident page

- keep/providers/elastic_provider/elastic_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4083
> feat: allow elastic provider self signed

- keep/providers/elastic_provider/elastic_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4083
> fix: elastic verify

- keep/api/core/demo_mode.py
close https://github.com/keephq/keep/issues/4099
> fix: remove removing of incidents

- keep-ui/app/(keep)/providers/provider-form-scopes.tsx
- keep/api/models/db/migrations/env.py
- keep/api/models/db/migrations/versions/2024-10-22-10-38_8438f041ee0e.py
- keep/api/models/db/migrations/versions/2025-03-12-14-46_ca74b4a04371.py
close https://github.com/keephq/keep/issues/4109
> fix: migrations fallback & few other things

- keep-ui/utils/hooks/useExpandedRows.ts
- pyproject.toml
close https://github.com/keephq/keep/issues/4071
> fix: use expanded

- keep-ui/auth.ts
- pyproject.toml
close https://github.com/keephq/keep/issues/4118
> fix: minor regex problem

- keep-ui/components/navbar/Menu.tsx
- keep-ui/components/navbar/Search.tsx
fixed cmd + k and:
https://github.com/user-attachments/assets/78f99b42-14fa-4232-99b7-b109d86bd4f9
> fix: navbar in smaller screens is broken

- keep-ui/app/(keep)/alerts/alert-table-column-rename.tsx
- keep-ui/app/(keep)/alerts/alert-table-headers.tsx
- keep-ui/app/(keep)/alerts/alert-table-rename.tsx
- keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep/api/models/alert.py
- keep/api/tasks/process_event_task.py
- keep/api/utils/enrichment_helpers.py
- keep/parser/parser.py
- tests/test_counting.py
- tests/test_counting_integration.py
close https://github.com/keephq/keep/issues/4125
> feat: add firing counter

- keep/parser/parser.py
- keep/workflowmanager/workflowstore.py
- tests/test_workflowstore.py
Refactored provider extraction to improve error handling and ensure robust parsing. Added unit tests for `get_workflow_meta_data` to validate behavior with valid and invalid workflows. This strengthens workflow parsing reliability and improves testing coverage.
Closes #3832
> fix: Refactor provider parsing and add workflow metadata tests

- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/app/(keep)/incidents/[id]/alerts/incident-alert-action-tray.tsx
- keep-ui/app/(keep)/incidents/[id]/alerts/incident-alerts.tsx
- keep-ui/entities/incidents/model/useIncidentActions.tsx
> feat: incident alerts table is compact now

- keep-ui/app/(keep)/mapping/[rule_id]/executions/page.tsx
> fix: csv preview

- docs/providers/documentation/telegram-provider.mdx
- examples/workflows/send-message-telegram-with-htmlmd.yaml
- keep/providers/telegram_provider/telegram_provider.py
Closes #4148
Added support for message formatting in telegram. Supports markdown and html
https://github.com/user-attachments/assets/873554e8-0d9a-43ef-ba07-e163173aba22
> feat: add formatting for telegram messages

- keep/api/bl/incidents_bl.py
- keep/api/tasks/process_event_task.py
- keep/rulesengine/rulesengine.py
> fix: prevent expire on commit during event processing

- keep/api/core/db.py
Replaced direct access to `incident.id` with a dedicated variable `incident_id`
Closes #4168
> fix: Refactor incident ID reference to prevent nested exception

- keep-ui/app/(keep)/incidents/[id]/chat/incident-chat.css
Closes #4054
https://github.com/user-attachments/assets/59ee3ea7-cff6-476e-b472-17f08d3f53b3
> fix: remove unnecessary height constraints from incident chat input

- keep/providers/grafana_provider/grafana_provider.py
close https://github.com/keephq/keep/issues/4192
> fix: grafana wrong fingerprint calc

- examples/workflows/opsgenie-close-alert.yml
- keep/providers/opsgenie_provider/opsgenie_provider.py
close https://github.com/keephq/keep/issues/4194
> feat: opsgenie close-alert

- keep/providers/cloudwatch_provider/cloudwatch_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4196
> fix: cloudwatch

- keep/api/routes/providers.py
- keep/providers/providers_factory.py
- pyproject.toml
- tests/test_provider_factory.py
close https://github.com/keephq/keep/issues/4200
> fix: get provider config name from db

- keep-ui/app/(keep)/rules/CorrelationSidebar/RuleFields.tsx
- keep-ui/app/(keep)/rules/CorrelationTable.tsx
- keep-ui/app/(keep)/rules/FormattedQueryCell.tsx
- keep-ui/app/(keep)/rules/GroupedByCel.tsx
- keep-ui/app/globals.css
- keep-ui/components/navbar/UserAvatar.tsx
Closes #2954
Closes #4206
Before:
https://github.com/user-attachments/assets/e275a0f5-fcac-4049-ac26-809d76960dd3
After:
https://github.com/user-attachments/assets/e5167905-d911-436d-bafc-d08d52746ad4
> fix: Fix layout to prevent scrollbar on Correlation rules page

- keep/api/models/db/migrations/versions/2025-03-18-14-54_971abbbf0a2c.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4214
> fix: migration

- keep-ui/app/(keep)/alerts/alert-table-utils.tsx
- keep-ui/shared/ui/utils/table-utils.ts
> fix(ui): source icons becoming small

- keep/api/arq_worker_gunicorn.py
close https://github.com/keephq/keep/issues/4224
> fix: no o11y in arq

- keep/api/logging.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4225
> fix: respect gunicorn log levels

- keep/api/core/alerts.py
- keep/api/core/db.py
- tests/test_alert_dto.py
> fix: bug startedate value is not honored when creating an alert through the generic event api

- keep-ui/entities/workflows/model/useWorkflowJsonSchema.ts
- keep-ui/entities/workflows/model/workflow-store.ts
- keep-ui/entities/workflows/model/yaml.schema.ts
- keep-ui/shared/ui/WorkflowYAMLEditor/ui/WorkflowYAMLEditor.tsx
- keep-ui/widgets/workflow-builder/workflow-builder.tsx
Closes #3676  
Changes are not saved if the workflow missing some props
https://github.com/user-attachments/assets/8d34ed10-745d-4cef-8de4-e97a74291f9c
Changes saved if something is missing but the general structure is correct
https://github.com/user-attachments/assets/bf44b756-7bb2-4093-92f9-77ad6091f397
> fix: validate agains loose workflow schema before syncing yaml editor

- keep/api/core/demo_mode.py
Added `safe_run_async_worker` to manage errors and enforce a restart threshold for async workers. Updated `simulate_alerts` to use the new wrapper, improving robustness and error handling.
Closes #4241
> fix: Refactor simulator async workers to handle errors and auto-restart.

- keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
Closes #3679  
https://github.com/user-attachments/assets/5ed6288d-6ab9-45f7-be83-8b6774d99875
https://github.com/user-attachments/assets/4bdeb43f-ad80-4a95-b65c-06ec14e0c8c4
> fix: fetching workflow test run logs for new workflows

- keep-ui/entities/workflows/model/schema.ts
- keep-ui/entities/workflows/model/types.ts
- keep-ui/entities/workflows/model/validation.ts
- keep-ui/entities/workflows/model/workflow-store.ts
- keep-ui/entities/workflows/model/yaml.schema.ts
- keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
> fix: workflow validation for mock provider

- keep/providers/pingdom_provider/pingdom_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4246
> fix: pingdom fingerprint

- keep/providers/providers_factory.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4249
> feat: a bit of logging for provider secrets

- keep/providers/pingdom_provider/pingdom_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4253
> feat: pingd

- keep/providers/pingdom_provider/pingdom_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4256
> fix: pingdom status

- keep-ui/app/(keep)/topology/topology-client.tsx
- keep/providers/pingdom_provider/pingdom_provider.py
- keep/providers/providers_factory.py
- pyproject.toml
Just noticed users "don't see it"
close https://github.com/keephq/keep/issues/4252
> fix: confusing topology refresh icon

- keep-ui/components/popover/GenericPopover.tsx
> feat: Add flip middleware to GenericPopover for improved positioning

- keep-ui/app/(keep)/deduplication/DeduplicationSidebar.tsx
- keep-ui/app/(keep)/deduplication/DeduplicationTable.tsx
- keep/api/alert_deduplicator/alert_deduplicator.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4273
> fix: dedup

- keep-ui/app/(keep)/incidents/[id]/incident-layout-client.tsx
- keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-header.tsx
- keep-ui/app/(keep)/workflows/[workflow_id]/workflow-overview.tsx
- keep-ui/app/(keep)/workflows/[workflow_id]/workflow-sync-status.tsx
- keep-ui/entities/workflows/model/useWorkflowDetail.ts
- keep-ui/shared/api/workflows.ts
- keep-ui/shared/ui/WorkflowYAMLEditor/ui/WorkflowYamlEditorHeader.tsx
- keep-ui/widgets/workflow-builder/workflow-builder-widget.tsx
- keep-ui/widgets/workflow-builder/workflow-builder.tsx
- keep/api/routes/workflows.py
- tests/e2e_tests/test_end_to_end.py
> feat: show wf revision in the UI

- keep-ui/app/globals.css
> fix: update Toastify styles to improve click interactions between toasts

- keep/providers/base/base_provider.py
close https://github.com/keephq/keep/issues/4283
> fix: fingerprint

- keep-ui/app/(keep)/workflows/[workflow_id]/workflow-sync-status.tsx
> fix: commas

- keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
- keep-ui/features/filter/facet.tsx
- keep-ui/features/filter/facets-panel.tsx
- keep-ui/features/filter/models.tsx
> feat: Allow users to select a facet even if there are no firing alerts

- keep-ui/app/(keep)/alerts/alert-preset-manager.tsx
before:
https://github.com/user-attachments/assets/b1e18a67-3073-484b-bfbc-ad23fe50bf96
after:
https://github.com/user-attachments/assets/4a089284-b62b-41b9-9057-97241d655b3a
> fix(ui): button color

- keep/providers/mailgun_provider/mailgun_provider.py
close https://github.com/keephq/keep/issues/4333
> fix: timestamp

- keep-ui/app/(keep)/layout.tsx
- keep-ui/components/LinkWithIcon.tsx
- keep-ui/components/navbar/AILink.tsx
- keep-ui/components/navbar/AlertsLinks.tsx
- keep-ui/components/navbar/CustomPresetAlertLinks.tsx
- keep-ui/components/navbar/IncidentLinks.tsx
- keep-ui/components/navbar/NoiseReductionLinks.tsx
- keep-ui/components/navbar/UserInfo.tsx
close https://github.com/keephq/keep/issues/4338
Before:
After:
> feat: navbar dense

- keep/parser/parser.py
close https://github.com/keephq/keep/issues/4339
> fix: interval int

- keep-ui/app/(keep)/layout.tsx
close https://github.com/keephq/keep/issues/4338
> fix: navbar dense

- keep-ui/components/navbar/DashboardLink.tsx
close https://github.com/keephq/keep/issues/4338
> fix: nav dashborad

- keep-ui/app/(keep)/alerts/alert-table-headers.tsx
- keep-ui/app/(keep)/alerts/alert-table-server-side.tsx
Closes #4122
https://github.com/user-attachments/assets/ca7a1b05-7320-4872-b224-f49d92219819
> fix: remove special handling for 'name' column in draggable header

- keep/api/routes/workflows.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4355
> fix: run workflow from incident

- tests/test_alert_evaluation.py
close https://github.com/keephq/keep/issues/3543
> fix: remove js2py

- keep-ui/app/(keep)/incidents/[id]/workflows/incident-workflow-sidebar.tsx
- keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-header.tsx
- keep-ui/app/(keep)/workflows/[workflow_id]/workflow-detail-page.tsx
- keep-ui/entities/workflow-executions/model/useWorkflowExecutionDetail.ts
- keep-ui/entities/workflow-executions/model/workflowExecutionsKeys.ts
- keep-ui/entities/workflows/model/useWorkflowDetail.ts
- keep-ui/features/workflow-execution-results/ui/WorkflowExecutionResults.tsx
- keep-ui/shared/api/workflow-executions.ts
- keep/api/core/db.py
- keep/api/routes/workflows.py
- keep/workflowmanager/workflowstore.py
> fix: workflow execution <null> in page title

- docs/snippets/providers/http-snippet-autogenerated.mdx
- docs/snippets/providers/telegram-snippet-autogenerated.mdx
- examples/workflows/telegram_basic.yml
- keep/providers/telegram_provider/telegram_provider.py
close https://github.com/keephq/keep/issues/4369
> feat: add telegram photo

- keep/providers/uptimekuma_provider/uptimekuma_provider.py
Introduce a reusable `_get_api` method to streamline API initialization and login. Add error handling for `BadNamespaceError` during monitor retrieval, including a single retry mechanism. Ensure proper disconnection after API usage to improve reliability.
Closes #4404
> fix: Refactor API handling and add retry on BadNamespaceError

- keep-ui/components/ui/DynamicProviderIcon.tsx
- keep-ui/shared/api/ApiClient.ts
> fix: prevent fallback icon infinite loop

- keep/api/models/db/migrations/versions/2025-04-03-12-09_bdf252fbc1be.py
- keep/api/models/db/migrations/versions/2025-04-06-12-18_78777e6b12d3.py
> fix: add migration to change dashboard_config column type to JSON

- keep/api/core/db.py
Updated the exception handling to catch OperationalError, ensuring better handling of deadlock scenarios during database operations. This change improves resilience against race conditions.
Closes #4435
> fix: Handle OperationalError instead of IntegrityError in db.py

- keep/api/core/db.py
Replaced custom retry mechanisms with `retry_on_race_condition` context manager to handle transactional deadlocks and stale data errors more cleanly. Consolidated logic for retries across multiple functions, improving maintainability and readability. Updated relevant functions to utilize the new context manager for consistent behavior.
Closes #4439
> fix: Refactor retry logic for database operations

- keep/api/core/db.py
Replaced custom retry implementations with a decorator-based approach for handling deadlocks and other exceptions. Simplified session management and error handling for database transactions to enhance readability and maintainability. Improved logging to provide better diagnostics during retries.
Closes #4439
> fix: Refactor database session handling and improve retry logic

- keep/providers/servicenow_provider/servicenow_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4443
> feat: a drop of logging for snow

- docker/Dockerfile.ui
- keep-ui/entrypoint.sh
- keep-ui/next.config.js
- pyproject.toml
close https://github.com/keephq/keep/issues/4456
> feat: sources

- keep-ui/next.config.js
- pyproject.toml
close https://github.com/keephq/keep/issues/4456
> fix: sources

- keep/api/core/facets.py
- keep/api/core/incidents.py
Closes #4466
- limit options per facet by 50
- fix forgotten filter by is_visible
> fix: Limit facet options per each facet

- keep/providers/servicenow_provider/servicenow_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4476
> fix: snow oauth via form-urlencoded

- docs/snippets/providers/splunk-snippet-autogenerated.mdx
- keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
- keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSubmission.tsx
- keep/api/bl/incidents_bl.py
- keep/api/core/db.py
- keep/api/tasks/process_incident_task.py
- keep/providers/cloudwatch_provider/cloudwatch_provider.py
- keep/providers/mailgun_provider/mailgun_provider.py
- keep/providers/splunk_provider/splunk_provider.py
- pyproject.toml
1. alerts in pulled incidents didn't appear
2. cloudwatch validate_scopes
3. mailgun provider empty alerts
4. create correlation button validation
5. splunk validate scopes
> fix: couple of different bugs

- .github/workflows/run-e2e-tests.yml
> fix: fix for E2E not running for contributors

- docs/snippets/providers/http-snippet-autogenerated.mdx
- keep/api/routes/providers.py
- keep/providers/http_provider/http_provider.py
- keep/providers/providers_service.py
- pyproject.toml
close #4508
close #4507 
close #4506
> feat: provision install webhook and http provider `fail_on_error`

- keep-ui/app/(keep)/topology/model/models.ts
- keep-ui/app/(keep)/topology/ui/map/getNodesAndEdgesFromTopologyData.ts
- keep-ui/app/(keep)/topology/ui/map/service-node.tsx
- keep-ui/app/(keep)/topology/ui/map/topology-map.tsx
- keep-ui/entities/alerts/model/types.ts
- keep-ui/entities/workflows/model/schema.ts
- keep-ui/widgets/alerts-table/lib/alert-table-utils.tsx
- keep-ui/widgets/alerts-table/ui/ColumnSelection.tsx
- keep-ui/widgets/alerts-table/ui/SettingsSelection.tsx
- keep-ui/widgets/alerts-table/ui/TitleAndFilters.tsx
- keep/api/models/incident.py
- keep/api/tasks/process_incident_task.py
- keep/providers/pagerduty_provider/pagerduty_provider.py
Before:
After:
After:
Provider name:
> fix: topology not showing alert count and a few more

- keep-ui/app/(keep)/dashboard/widget-types/preset/columns-selection.tsx
- keep-ui/app/(keep)/dashboard/widget-types/preset/widget-alerts-table.tsx
- pyproject.toml
> fix: Replace toSorted with slice and sort for consistent column ordering

- keep-ui/app/(keep)/topology/ui/map/getLayoutedElements.ts
Fix for the incident topology
close https://github.com/keephq/keep/issues/4455
> fix: topology for the incident

- docs/snippets/providers/http-snippet-autogenerated.mdx
- docs/snippets/providers/prometheus-snippet-autogenerated.mdx
- keep/providers/grafana_provider/grafana_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4548
> feat: more verbose

- keep/providers/uptimekuma_provider/uptimekuma_provider.py
Refactor `STATUS_MAP` to include more status mappings for alerts and utilize `.value` for consistency. Improve datetime handling with a new `_format_datetime` method to adjust based on timezone offsets.
Closes #4550
> fix: Update UptimeKuma status handling and datetime formatting

- keep/providers/gcpmonitoring_provider/gcpmonitoring_provider.py
Simplified and clarified content assignment logic by adjusting how the "content" attribute is set. This ensures proper handling in both alert and test notification scenarios.
Closes #4554 4554
> fix: Refactor content initialization in GCPMonitoring provider

- keep-ui/app/(keep)/topology/ui/TopologySearchAutocomplete.tsx
- keep-ui/app/(keep)/topology/ui/applications/create-or-update-application-form.tsx
close https://github.com/keephq/keep/issues/2445
Just a simple fallback
> fix: topology services without names

- docs/snippets/providers/prometheus-snippet-autogenerated.mdx
- keep/providers/prometheus_provider/prometheus_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4580
> feat: self signed cert support for prometheus

- keep/api/models/db/migrations/versions/2025-04-15-15-30_885ff6b12fed.py
- keep/api/models/db/workflow.py
> fix: wf versions migration

- keep/api/core/workflows.py
> fix:  Workflow facets stop updating when using search

- keep/api/core/db.py
- keep/providers/keep_provider/keep_provider.py
- keep/workflowmanager/workflowstore.py
- pyproject.toml
Fix generating of workflow duplicates while updating them from s3
close https://github.com/keephq/keep/issues/4623
> fix: workflow-updating-via-s3

- keep/api/core/facets.py
Closes #4626
Close keep incident bb3ed92b-63c5-4c0c-aa31-63a58e6d15a1
> fix: Handle None property metadata in facet selection

- keep-ui/app/(keep)/incidents/[id]/timeline/incident-timeline.tsx
Updated the incident timeline with enhanced column spans for better readability and added alert fingerprint details for more context. Adjusted card styling and heights for a more responsive layout while making the time labels sticky for improved navigation.
Closes #4618
Fixed scrolling issues + UI is now more suitable for long texts
Before:
After:
> fix: Improve timeline layout and add alert fingerprint display

- keep-ui/middleware.ts
This change ensures that the /api/healthcheck endpoint is accessible without authentication. It aligns with the intention to make health checks publicly available for monitoring purposes.
Closes #4393
> fix: Update middleware to exclude /api/healthcheck from auth

- keep-ui/features/presets/presets-manager/ui/alerts-rules-builder.tsx
> fix: Fix bug causing E2E to fail

- .gitignore
- pyproject.toml
> chore: bump version `0.42.2`

- keep/providers/kubernetes_provider/kubernetes_provider.py
- keep/providers/zabbix_provider/zabbix_provider.py
- pyproject.toml
> fix: 4238 bug zabbix provider is not compatible with zabbix 60 and zabbix 62

- keep/providers/pagerduty_provider/pagerduty_provider.py
close https://github.com/keephq/keep/issues/4681
> fix: pagerduty with `unkown` title

- keep-ui/features/filter/build-cel.test.ts
- keep-ui/features/filter/build-cel.ts
> fix: Fix bug when clicking on severity/status 0 matched option showed all alerts

- keep/providers/site24x7_provider/site24x7_provider.py
> fix: Use INCIDENT_TIME_ISO instead of INCIDENT_TIME for site24x7 provider

- keep/providers/kibana_provider/kibana_provider.py
close https://github.com/keephq/keep/issues/4690
> fix: kibana name

- keep/providers/grafana_provider/grafana_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4661
> feat: grafana datasource-managed alerts

- keep/api/core/db.py
- tests/provision/workflows_4/console_example.yml
- tests/test_workflow_execution.py
> fix: test wf provisioning

- keep-ui/shared/ui/MonacoCELEditor/monaco-cel-editor.tsx
- pyproject.toml
> fix: Fix incorrectly set value to monaco editor in CelInput

- keep/providers/kubernetes_provider/kubernetes_provider.py
- pyproject.toml
> fix: k8s failed to run `list_namespaced_event`

- keep/api/core/cel_to_sql/cel_ast_converter.py
- tests/cel_to_sql/test_cel_to_ast.py
> fix: CEL query with dictionary like property access work incorrectly

- ee/identitymanager/identity_managers/keycloak/keycloak_authverifier.py
- keycloak/KEYCLOAK_LDAP.md
- keycloak/ldif/ldap_orgs_new.ldif
- pyproject.toml
close https://github.com/keephq/keep/issues/4726
> fix: keycloak multiorg

- keep/providers/providers_service.py
- pyproject.toml
- tests/conftest.py
- tests/test_provisioning.py
> fix: provisioning providers with no auth config

- keep/api/core/db.py
> fix: `psycopg2.errors.NotNullViolation` while updating workflows 

- keep/providers/grafana_loki_provider/grafana_loki_provider.py
- pyproject.toml
> fix: Fix hidden "Enable SSL verification" for Grafana Loki provider

- keep-ui/features/presets/presets-manager/ui/alerts-rules-builder.tsx
> fix: cant save a valid CEL expression

- keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationForm.tsx
- keep-ui/app/(keep)/rules/CorrelationSidebar/CorrelationSidebarBody.tsx
- keep-ui/app/(keep)/rules/CorrelationSidebar/index.tsx
- keep-ui/app/(keep)/rules/CorrelationSidebar/types.ts
- keep-ui/utils/hooks/useRules.ts
- keep/api/core/db.py
- keep/api/models/db/migrations/versions/2025-05-15-00-34_fcef2c58b21c.py
- keep/api/models/db/rule.py
- keep/api/routes/rules.py
- keep/rulesengine/rulesengine.py
- tests/test_rules_engine.py
> feat: Add threshold support for Correlation Rule

- docs/workflows/syntax/functions.mdx
- keep/functions/__init__.py
- tests/test_functions.py
- tests/test_iohandler.py
Closes #4736 
This PR adds mathematical functions to Keep
> feat: add arithmetic operations to keep built in functions

- keep/api/models/db/migrations/versions/2025-05-15-14-18_bedb5f07417b.py
> fix: merge migrations heads

- keep/providers/pagerduty_provider/pagerduty_provider.py
Reverts keephq/keep#4680
close https://github.com/keephq/keep/issues/4812
> fix: Revert "feat: Pagerduty Provider: incident enrichments #4663"

- keep/api/core/elastic.py
> feat: Make elastic index refresh strategy configurable via env variable

- keep-ui/app/(keep)/workflows/workflow-graph.tsx
> fix: workflow-graph caused by type: "linear"

- keep/cli/cli.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4780
> fix: permissions on `cli.py`

- keep/identitymanager/identity_managers/oauth2proxy/oauth2proxy_identitymanager.py
close https://github.com/keephq/keep/issues/4821
> fix: delete_user

- keep/api/core/db.py
> fix: Catch also IntegrityError, StaleDataError in retry_on_db_error

- keep/providers/keep_provider/keep_provider.py
- pyproject.toml
- tests/test_workflows.py
close https://github.com/keephq/keep/issues/4799
> feat: wf alert postgres

- keep-ui/components/ui/Modal.tsx
- keep-ui/features/workflows/manual-run-workflow/ui/manual-run-workflow-modal.tsx
- keep-ui/widgets/alerts-table/ui/alert-table-server-side.tsx
- pyproject.toml
- tests/e2e_tests/test_end_to_end.py
- tests/e2e_tests/workflow-alert-log.yaml
- tests/e2e_tests/workflow-incident-log.yaml
> fix: no workflows found for execution from alert or incident

- docs/deployment/kubernetes/installation.mdx
Closes https://github.com/keephq/keep/issues/4860
fix helm chart upgrade
> docs: installation.mdx to fix helm upgrade values for TLS

- keep-ui/entities/workflows/model/workflow-yaml-editor-store.ts
- keep-ui/features/workflows/test-run/model/useWorkflowTestRun.ts
- keep-ui/features/workflows/test-run/ui/workflow-test-run-button.tsx
- keep-ui/widgets/workflow-builder/workflow-builder.tsx
- tests/e2e_tests/test_end_to_end.py
> fix: event body in workflow test runs

- keep/providers/statuscake_provider/statuscake_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4890
> fix: statuscake uptime alerts

- keep/providers/statuscake_provider/statuscake_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/4916
> fix: statuscake

- tests/conftest.py
- tests/e2e_tests/test_end_to_end_db_auth.py
- tests/e2e_tests/test_pushing_prometheus_alerts.py
- tests/test_enrichments.py
> fix: flaky tests

- keep-ui/features/alerts/view-raw-alert/ui/ViewAlertModal.tsx
- keep-ui/widgets/alerts-table/lib/alert-table-time-format.tsx
- keep/api/models/alert.py
- keep/api/tasks/process_event_task.py
- keep/api/utils/enrichment_helpers.py
> feat: firingStartTimeSinceLastResolved

- keep/api/core/cel_to_sql/ast_nodes.py
- keep/api/core/cel_to_sql/cel_ast_converter.py
- keep/api/core/cel_to_sql/properties_mapper.py
- keep/api/core/cel_to_sql/properties_metadata.py
- keep/api/core/cel_to_sql/sql_providers/base.py
- keep/api/core/cel_to_sql/sql_providers/mysql.py
- keep/api/core/cel_to_sql/sql_providers/postgresql.py
- keep/api/core/cel_to_sql/sql_providers/sqlite.py
- tests/cel_to_sql/cel-to-sql-test-cases.json
- tests/cel_to_sql/test_cel_to_ast.py
> fix: Implement "has" CEL operator support

- keep/api/core/cel_to_sql/cel_ast_converter.py
> fix: Add logging for errors in CEL to AST conversion

- keep/providers/base/base_provider.py
- pyproject.toml
- tests/test_workflows.py
close https://github.com/keephq/keep/issues/4934
> feat: support enrich array

- keep/providers/keep_provider/keep_provider.py
- pyproject.toml
- tests/test_alert_evaluation.py
- tests/test_workflows.py
close https://github.com/keephq/keep/issues/4958
> fix: alert evaluation

- pyproject.toml
> chore: bump version from 0.45.1 to 0.45.2

- pyproject.toml
> build: bump version to 0.45.4

- keep/identitymanager/authverifierbase.py
> fix: Log request headers in case of No valid authentication method found

- keep-ui/components/ui/Modal.tsx
- tests/e2e_tests/test_end_to_end.py
> fix: flacky e2e test `test_run_workflow_from_alert_and_incident`

- tests/e2e_tests/test_end_to_end.py
- tests/e2e_tests/workflow-interval.yaml
> feat: add end-to-end test for interval workflow

- keep/api/tasks/process_event_task.py
- keep/api/utils/alert_utils.py
- tests/test_alert_utils.py
> fix: Add alert body sanitizer

- .github/workflows/release-workflow-schema.yml
- keep/providers/providers_factory.py
> fix: update release-workflow-schema.yml, skip schema repo checkout for forks

- keep-ui/components/navbar/IncidentLinks.tsx
- keep-ui/components/navbar/NoiseReductionLinks.tsx
- tests/e2e_tests/test_end_to_end.py
> fix: Make tests more stable

- docs/authentication/okta.md
- docs/deployment/authentication/overview.mdx
- docs/deployment/configuration.mdx
- keep-ui/app/(signin)/error/authEnvUtils.tsx
- keep-ui/app/(signin)/signin/SignInForm.tsx
- keep-ui/auth.config.ts
- keep-ui/utils/authenticationType.ts
- keep/identitymanager/identity_managers/okta/okta_authverifier.py
- keep/identitymanager/identity_managers/okta/okta_identitymanager.py
- keep/identitymanager/identitymanagerfactory.py
- Add OktaAuthVerifier for JWT token validation with JWKS
- Add OktaIdentityManager with basic SSO support (management functions disabled)
- Add Okta provider configuration in auth.config.ts
- Add Okta to AuthType enum and environment variable handling
- Add comprehensive Okta integration documentation
- Support automatic token refresh for Okta sessions
This enables Okta SSO authentication with:
- JWKS-based token verification with caching
- Configurable tenant and role extraction from tokens
- Automatic key refresh on validation failure
- NextAuth.js integration for seamless authentication flow
closes #5197
> feat: add Okta authentication support

- keep/providers/pushover_provider/pushover_provider.py
close https://github.com/keephq/keep/issues/5218
This PR adds support for configuring [Pushover](https://pushover.net/) notification sound and message priority directly via the provider UI and YAML config.
This allows users to customize how alerts are delivered, including:
•	sound (e.g. bike, pushover, alien, etc.)
•	priority (-2=No Alert, -1=Quiet, 0=Normal, 1=High, 2=Emergency)
Both fields are optional and default to "pushover" sound and 0 priority if not specified.
New Look
Old Look
> feat: add sound and priority support to pushover provider

- keep-ui/next_build.sh
- keep/api/api.py
- keep/api/bl/dismissal_expiry_bl.py
- pyproject.toml
- tests/test_dismissal_expiry_bug.py
close https://github.com/keephq/keep/issues/5047
> fix: dismiss until

- keep/providers/grafana_provider/grafana_provider.py
- keep/providers/kibana_provider/kibana_provider.py
- pyproject.toml
close https://github.com/keephq/keep/issues/5285
> feat: graf

- keep/providers/libre_nms_provider/libre_nms_provider.py
Added a fix for a "miss documentation" for the LibreNMS provider. This will state clearer how to change settings from linked to connected binding.
close https://github.com/keephq/keep/issues/5346
> docs: Documentation fix for LibreNMS provider
